sonar.projectKey=DigitalInnovation_trading-hub
sonar.organization=digitalinnovation

sonar.junit.reportPaths=junit.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.spec.js
