import {
  AttributesResponse,
  AttributeValuesResponse,
  BetaMerchandisingFacetListData,
  Categories,
  ProductSearchResponse,
  ReturnedCategoryRuleSet,
  ReturnedCategoryRuleSets,
  SearchPreviewResponseBeta,
} from '@/libs/api';

export const mockCategoryRulesets: ReturnedCategoryRuleSets = {
  ruleSets: [
    {
      id: '5e1002e8-bb08-4215-b26f-b5f6814b010a',
      isEnabled: true,
      rules: {
        pinnedProducts: [
          { id: 'T27-3186L-202105' },
          { id: 'T27-3130L-202105' },
          { id: 'T27-3157L-202105' },
          { id: 'T27-3161L-202105' },
        ],
        blockedProducts: [],
        boosts: {
          numeric: [{ field: 'newInFreshNess', weight: 100 }],
          alphanumeric: [
            {
              fields: [{ field: 'colourGroup', values: ['Beige'] }],
              weight: 100,
            },
          ],
          product: [
            { id: 'T27-3160L-202105', weight: 100 },
            { id: 'T27-3162L-202105', weight: 100 },
          ],
        },
        buries: { numeric: [], alphanumeric: [], product: [] },
        includes: { alphanumeric: [] },
        excludes: { alphanumeric: [] },
      },
      lastChanged: { date: '2024-09-19T14:58:20Z', user: 'Graham Licence' },
      facets: [
        {
          id: '4f8d4803-3eb0-11ef-9a6a-000000000000',
          excludedValues: ['NO COLOUR'],
          boosted: ['CHAMPAGNE'],
        },
        {
          id: 'a43271cf-bf57-4e40-8fe3-f3d59f9c4c2e',
          excludedValues: [],
          boosted: ['SC_Level_0_0', 'SC_Level_1_16696340'],
        },
      ],
      categoriesInfo: [
        {
          id: 'SubCategory_2933925',
          name: 'Lamp Shades',
          plpUrl: 'l/furniture/lighting/lamp-shades',
        },
      ],
      excludedFacets: { facets: [] },
      startDate: '2024-09-12T14:17:54Z',
      endDate: '2024-12-19T04:20:03Z',
    },
    {
      id: '22ce8ae9-a7b3-4a52-bea4-e31ebf1f5f10',
      isEnabled: false,
      rules: {
        pinnedProducts: [],
        blockedProducts: [],
        boosts: { numeric: [], alphanumeric: [], product: [] },
        buries: { numeric: [], alphanumeric: [], product: [] },
        includes: { alphanumeric: [] },
        excludes: { alphanumeric: [] },
      },
      lastChanged: { date: '2024-09-16T09:34:22Z', user: 'Nikolay Gushchin' },
      facets: [
        {
          id: '4f8ecea1-3eb0-11ef-9a6a-000000000000',
          excludedValues: [],
          boosted: [],
        },
        {
          id: '528e50d2-5f32-4248-868b-72cdce842597',
          excludedValues: ['Brown'],
          boosted: ['Pink', 'Navy', 'Grey', 'Blue', 'Green'],
        },
        {
          id: '08aa7156-7b45-4399-a24f-345f110ed327',
          excludedValues: [],
          boosted: [],
        },
      ],
      categoriesInfo: [
        { id: 'SubCategory_429', name: 'Dresses', plpUrl: 'l/women/dresses' },
      ],
      excludedFacets: {
        facets: [
          { id: '1e404940-3240-11ef-aa09-000000000000' },
          { id: '1e742a80-3240-11ef-aa09-000000000000' },
        ],
      },
    },
    {
      id: '9d7f6ae7-2653-4eb6-b51b-1ee6f4087cce',
      isEnabled: false,
      rules: {
        pinnedProducts: [
          { id: '60529551' },
          { id: '60509242' },
          { id: '60529576' },
          { id: '60530263' },
        ],
        blockedProducts: [],
        boosts: {
          numeric: [],
          alphanumeric: [],
          product: [{ id: '60533104', weight: 100 }],
        },
        buries: { numeric: [], alphanumeric: [], product: [] },
        includes: { alphanumeric: [] },
        excludes: { alphanumeric: [] },
      },
      lastChanged: { date: '2024-09-16T08:59:27Z', user: 'Graham Licence' },
      facets: [],
      categoriesInfo: [
        {
          id: 'SubCategory_20584814',
          name: 'Mens',
          plpUrl: 'l/cold-weather/cold-weather/mens',
        },
      ],
      excludedFacets: { facets: [] },
    },
    {
      id: 'd9cb14fd-bed0-4d95-822a-743edd44a624',
      isEnabled: true,
      rules: {
        pinnedProducts: [],
        blockedProducts: [],
        boosts: {
          numeric: [],
          alphanumeric: [],
          product: [{ id: '22533393', weight: 100 }],
        },
        buries: { numeric: [], alphanumeric: [], product: [] },
        includes: { alphanumeric: [] },
        excludes: { alphanumeric: [] },
      },
      lastChanged: { date: '2024-09-12T11:24:05Z', user: 'James Winfield' },
      facets: [
        {
          id: 'f0421b40-563e-11ef-a364-000000000000',
          excludedValues: [],
          boosted: [],
        },
        {
          id: '528e50d2-5f32-4248-868b-72cdce842597',
          excludedValues: ['Brown'],
          boosted: ['Pink', 'Navy', 'Grey', 'Blue', 'Green'],
        },
        {
          id: 'a43271cf-bf57-4e40-8fe3-f3d59f9c4c2e',
          excludedValues: [],
          boosted: [],
        },
      ],
      categoriesInfo: [
        { id: 'SubCategory_429', name: 'Dresses', plpUrl: 'l/women/dresses' },
      ],
      excludedFacets: {
        facets: [{ id: '4f8d4801-3eb0-11ef-9a6a-000000000000' }],
      },
    },
    {
      id: 'f2bd8b23-9986-4d15-9cc7-a1340403be11',
      isEnabled: true,
      rules: {
        pinnedProducts: [],
        blockedProducts: [],
        boosts: { numeric: [], alphanumeric: [], product: [] },
        buries: { numeric: [], alphanumeric: [], product: [] },
        includes: { alphanumeric: [] },
        excludes: { alphanumeric: [] },
      },
      lastChanged: { date: '2024-09-11T12:20:13Z', user: 'James Winfield' },
      facets: [],
      categoriesInfo: [
        { id: 'SubCategory_26759315', name: 'Jeans', plpUrl: 'l/women/jeans' },
      ],
      excludedFacets: { facets: [] },
    },
    {
      id: '72712f3f-345f-490b-a04e-1dfadc3a9704',
      isEnabled: true,
      rules: {
        pinnedProducts: [{ id: '22531832' }],
        blockedProducts: [
          { id: '22533393' },
          { id: '22533324' },
          { id: '22530871' },
          { id: '22533840' },
          { id: '22532571' },
          { id: '22533303' },
          { id: '60529550' },
          { id: '60530084' },
          { id: '60530166' },
          { id: '60529551' },
          { id: '60533104' },
          { id: '60531732' },
          { id: '60529576' },
          { id: '60529552' },
          { id: '60530263' },
          { id: '60530509' },
          { id: '22534132' },
          { id: '60519903' },
        ],
        boosts: {
          numeric: [],
          alphanumeric: [],
          product: [
            { id: '22532566', weight: 100 },
            { id: '22534400', weight: 100 },
            { id: '60519891', weight: 100 },
            { id: '60529580', weight: 100 },
          ],
        },
        buries: {
          numeric: [],
          alphanumeric: [],
          product: [
            { id: '60519733', weight: 100 },
            { id: '60543680', weight: 100 },
          ],
        },
        includes: { alphanumeric: [] },
        excludes: { alphanumeric: [] },
      },
      lastChanged: { date: '2024-09-11T11:26:49Z', user: 'Nikolay Gushchin' },
      facets: [],
      categoriesInfo: [
        { id: 'SubCategory_429', name: 'Dresses', plpUrl: 'l/women/dresses' },
      ],
      excludedFacets: {
        facets: [{ id: '1e742a80-3240-11ef-aa09-000000000000' }],
      },
    },
    {
      id: '2ab7aaff-0d5c-4617-a8a6-fc6fb3f531f0',
      isEnabled: false,
      rules: {
        pinnedProducts: [
          { id: '60530142' },
          { id: '60505743' },
          { id: '60287451' },
          { id: '60543187' },
          { id: '60287468' },
          { id: '60527107' },
          { id: '60543188' },
          { id: '60524086' },
          { id: '60528711' },
          { id: '60287442' },
          { id: '60526988' },
          { id: '60521358' },
          { id: '60137777' },
        ],
        blockedProducts: [],
        boosts: { numeric: [], alphanumeric: [], product: [] },
        buries: { numeric: [], alphanumeric: [], product: [] },
        includes: { alphanumeric: [] },
        excludes: { alphanumeric: [] },
      },
      lastChanged: { date: '2024-09-10T15:56:30Z', user: 'Krzysztof Kabat' },
      facets: [
        {
          id: '51433560-3eb0-11ef-9a6a-000000000000',
          excludedValues: [],
          boosted: [],
        },
      ],
      categoriesInfo: [
        {
          id: 'SubCategory_26224922',
          name: "Men's Shirts",
          plpUrl: 'l/men/mens-shirts',
        },
      ],
      excludedFacets: { facets: [] },
    },
  ],
  pagination: { totalItems: 7 },
};

export const mockCategoryRuleset: ReturnedCategoryRuleSet = {
  id: '5e1002e8-bb08-4215-b26f-b5f6814b010a',
  isEnabled: true,
  rules: {
    pinnedProducts: [
      { id: 'T27-3186L-202105' },
      { id: 'T27-3130L-202105' },
      { id: 'T27-3157L-202105' },
      { id: 'T27-3161L-202105' },
    ],
    blockedProducts: [],
    boosts: {
      numeric: [{ field: 'newInFreshNess', weight: 100 }],
      alphanumeric: [
        { fields: [{ field: 'colourGroup', values: ['Beige'] }], weight: 100 },
      ],
      product: [
        { id: 'T27-3160L-202105', weight: 100 },
        { id: 'T27-3162L-202105', weight: 100 },
      ],
    },
    buries: { numeric: [], alphanumeric: [], product: [] },
    includes: { alphanumeric: [] },
    excludes: { alphanumeric: [] },
  },
  lastChanged: { date: '2024-09-19T14:58:20Z', user: 'Graham Licence' },
  facets: [
    {
      id: '4f8d4803-3eb0-11ef-9a6a-000000000000',
      excludedValues: ['NO COLOUR'],
      boosted: ['CHAMPAGNE'],
    },
    {
      id: 'a43271cf-bf57-4e40-8fe3-f3d59f9c4c2e',
      excludedValues: [],
      boosted: ['SC_Level_0_0', 'SC_Level_1_16696340'],
    },
  ],
  categoriesInfo: [
    {
      id: 'SubCategory_2933925',
      name: 'Lamp Shades',
      plpUrl: 'l/furniture/lighting/lamp-shades',
    },
  ],
  excludedFacets: { facets: [] },
  startDate: '2024-09-12T14:17:54Z',
  endDate: '2024-12-19T04:20:03Z',
};

export const mockCategoryList: Categories = {
  categories: [
    { identifier: 'SubCategory_429', name: 'Dresses', path: 'l/women/dresses' },
    {
      identifier: 'SubCategory_841578',
      name: 'Dresses',
      path: 'l/women/all-new-in/clothing/dresses',
    },
    {
      identifier: 'SubCategory_25090153',
      name: 'Dresses',
      path: 'l/kids/girls/dresses',
    },
    {
      identifier: 'SubCategory_25088326',
      name: 'Dresses',
      path: 'l/kids/baby/dresses',
    },
  ],
  pagination: { totalItems: 4 },
};

export const mockPreview: SearchPreviewResponseBeta = {
  category: 'SubCategory_429',
  ruleSet: {
    rules: {
      pinnedProducts: [],
      blockedProducts: [],
      boosts: {
        numeric: [],
        alphanumeric: [],
        product: [],
      },
      buries: {
        numeric: [],
        alphanumeric: [],
        product: [],
      },
      includes: {
        alphanumeric: [],
      },
      excludes: {
        alphanumeric: [],
      },
    },
    facets: [],
  },
  products: [
    {
      id: '60529550',
      productId: '60529550',
      title: 'V-Neck Knee Length Swing Dress',
      url: 'v-neck-knee-length-smock-dress/p/clp60529552?color=BLACK&image=SD_10_T97_6310B_Y0_X_EC_90',
      price: '£125.00',
      brand: 'JAEGER',
      isInStock: true,
      imageUrl: ['SD_10_T97_6310B_Y0_X_EC_90', 'SD_10_T97_6310B_Y0_X_EC_90'],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60529551',
      productId: '60529551',
      title: 'V-Neck Knee Length Swing Dress',
      url: 'v-neck-knee-length-smock-dress/p/clp60529552?color=KHAKI&image=SD_10_T97_6310B_KH_X_EC_90',
      price: '£125.00',
      brand: 'JAEGER',
      isInStock: false,
      imageUrl: [
        'SD_10_T97_6310B_KH_X_EC_0',
        'SD_10_T97_6310B_KH_X_EC_0',
        'SD_10_T97_6310B_KH_X_EC_90',
        'SD_10_T97_6310B_KH_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60533104',
      productId: '60533104',
      title: 'Gingham Pleated Midi Shirt Dress',
      url: 'gingham-pleated-midi-shirt-dress/p/clp60530257?color=NAVY&image=SD_10_T97_6331B_F0_X_EC_90',
      price: '£175.00',
      brand: 'JAEGER',
      isInStock: true,
      imageUrl: [
        'SD_10_T97_6331B_F0_X_EC_0',
        'SD_10_T97_6331B_F0_X_EC_0',
        'SD_10_T97_6331B_F0_X_EC_90',
        'SD_10_T97_6331B_F0_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60529580',
      productId: 'P60529580',
      title: 'Crepe Contrast Detailing Shift Dress',
      url: 'crepe-contrast-detailing-shift-dress/p/clp60529580?color=BLACKMIX&image=SD_10_T97_6309B_Y4_X_EC_90',
      price: '£125.00',
      brand: 'JAEGER',
      isInStock: false,
      imageUrl: [
        'SD_10_T97_6309B_Y4_X_EC_0',
        'SD_10_T97_6309B_Y4_X_EC_0',
        'SD_10_T97_6309B_Y4_X_EC_90',
        'SD_10_T97_6309B_Y4_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60531732',
      productId: 'P60531732',
      title: 'Pure Silk Animal Print V-Neck Shift Dress',
      url: 'pure-silk-animal-print-v-neck-shift-dress/p/clp60531732?color=BLACK/WHITE&image=SD_10_T97_6346B_YZ_X_EC_90',
      price: '£199.00',
      brand: 'JAEGER',
      isInStock: true,
      imageUrl: [
        'SD_10_T97_6346B_YZ_X_EC_0',
        'SD_10_T97_6346B_YZ_X_EC_0',
        'SD_10_T97_6346B_YZ_X_EC_90',
        'SD_10_T97_6346B_YZ_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60529576',
      productId: '60529576',
      title: 'Crepe Tie Neck Knee Length Shift Dress',
      url: 'crepe-tie-neck-knee-length-shift-dress/p/clp60529576?color=NAVYMIX&image=SD_10_T97_6308B_F4_X_EC_90',
      price: '£125.00',
      brand: 'JAEGER',
      isInStock: true,
      imageUrl: [
        'SD_10_T97_6308B_F4_X_EC_0',
        'SD_10_T97_6308B_F4_X_EC_0',
        'SD_10_T97_6308B_F4_X_EC_90',
        'SD_10_T97_6308B_F4_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60529552',
      productId: '60529552',
      title: 'V-Neck Knee Length Swing Dress',
      url: 'v-neck-knee-length-smock-dress/p/clp60529552?color=NAVY&image=SD_10_T97_6310B_F0_X_EC_90',
      price: '£125.00',
      brand: 'JAEGER',
      isInStock: true,
      imageUrl: ['SD_10_T97_6310B_KH_X_EC_0', 'SD_10_T97_6310B_KH_X_EC_0'],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60530166',
      productId: 'P60530166',
      title: 'Wool Rich Funnel Neck Dress',
      url: 'wool-rich-funnel-neck-reversible-dress/p/clp60530166?color=OLIVEMIX&image=SD_10_T97_6341B_BX_X_EC_90',
      price: '£135.00',
      brand: 'JAEGER',
      isInStock: true,
      imageUrl: [
        'SD_10_T97_6341B_BX_X_EC_0',
        'SD_10_T97_6341B_BX_X_EC_0',
        'SD_10_T97_6341B_BX_X_EC_90',
        'SD_10_T97_6341B_BX_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60530084',
      productId: '60530084',
      title: 'Pure Wool Ribbed Midi Bodycon Dress',
      url: 'pure-wool-ribbed-midi-bodycon-dress/p/clp60530084?color=OLIVE&image=SD_10_T97_6340B_JR_X_EC_90',
      price: '£150.00',
      brand: 'JAEGER',
      isInStock: true,
      imageUrl: [
        'SD_10_T97_6340B_JR_X_EC_0',
        'SD_10_T97_6340B_JR_X_EC_0',
        'SD_10_T97_6340B_JR_X_EC_90',
        'SD_10_T97_6340B_JR_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60530263',
      productId: 'P60530263',
      title: 'Star Print V-Neck Ruffle Midi Tiered Dress',
      url: 'star-print-v-neck-ruffle-midi-tiered-dress/p/clp60530263?color=BLACK/WHITE&image=SD_10_T97_6306B_YZ_X_EC_90',
      price: '£199.00',
      brand: 'JAEGER',
      isInStock: true,
      imageUrl: [
        'SD_10_T97_6306B_YZ_X_EC_0',
        'SD_10_T97_6306B_YZ_X_EC_0',
        'SD_10_T97_6306B_YZ_X_EC_90',
        'SD_10_T97_6306B_YZ_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
  ],
  externalChanges: {
    pinnedProducts: [],
    blockedProducts: [
      {
        id: '60099727',
        productId: 'P60099727',
        title: "2pk Boys' Easy Dressing School Shorts (3-14 Yrs)",
        url: '2-pack-boys-adaptive-shorts/p/clp60099727?color=GREY&image=SD_04_T76_4912_T0_X_EC_90',
        price: '£8.00-£12.00',
        brand: 'M&S Collection',
        isInStock: true,
        imageUrl: [
          'SD_04_T76_4912_T0_X_EC_0',
          'SD_04_T76_4912_T0_X_EC_0',
          'SD_04_T76_4912_T0_X_EC_90',
          'SD_04_T76_4912_T0_X_EC_90',
        ],
        metadata: {
          isPinned: false,
          isBoosted: false,
          isBuried: false,
          isBlocked: false,
        },
      },
      {
        id: '60515136',
        productId: 'P60515136',
        title: 'Alphabet Jewellery Box',
        url: 'alphabet-jewellery-box/p/hbp60515136?color=GREY&image=PL_05_T27_8506B_T0_X_EC_90',
        price: '£9.50',
        isInStock: true,
        imageUrl: [
          'PL_05_T27_8506B_T0_X_EC_0',
          'PL_05_T27_8506B_T0_X_EC_0',
          'PL_05_T27_8506B_T0_X_EC_90',
          'PL_05_T27_8506B_T0_X_EC_90',
        ],
        metadata: {
          isPinned: false,
          isBoosted: false,
          isBuried: false,
          isBlocked: false,
        },
      },
    ],
    boosts: {
      numeric: [
        {
          field: 'predictions.revenueIn1Day.normalisedValue',
          weight: 6,
        },
        {
          field: 'newInFreshNess',
          weight: 0.25,
        },
      ],
      alphanumeric: [
        {
          fields: [
            {
              field: 'brand',
              values: ['JAEGER'],
            },
          ],
          weight: 100,
        },
      ],
      product: [
        {
          id: '60508654',
          productId: '60508654',
          title: 'Egyptian Cotton Luxury Towel',
          url: 'egyptian-cotton-towel/p/hbp60508646?color=COBALT&image=PL_05_T36_1917E_CB_X_EC_90',
          price: '£2.00-£18.00',
          isInStock: true,
          imageUrl: [
            'PL_05_T36_1917E_CB_X_EC_0',
            'PL_05_T36_1917E_CB_X_EC_0',
            'PL_05_T36_1917E_CB_X_EC_90',
            'PL_05_T36_1917E_CB_X_EC_90',
          ],
          metadata: {
            isPinned: false,
            isBoosted: false,
            isBuried: false,
            isBlocked: false,
          },
          weight: 100,
        },
      ],
    },
    buries: {
      numeric: [],
      alphanumeric: [],
      product: [],
    },
    includes: {
      alphanumeric: [],
    },
    excludes: {
      alphanumeric: [],
    },
  },
  facets: [
    {
      id: 'Colour',
      order: 2,
      data: [
        {
          count: 18,
          name: 'Pink',
          colourHexValue: '#FF3399',
          iconValue: 'product.colours.pink',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 61,
          name: 'Navy',
          colourHexValue: '#012856',
          iconValue: 'product.colours.navy',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 13,
          name: 'Grey',
          colourHexValue: '#808080',
          iconValue: 'product.colours.grey',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 37,
          name: 'Blue',
          colourHexValue: '#0000FF',
          iconValue: 'product.colours.blue',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 55,
          name: 'Green',
          colourHexValue: '#63CB11',
          iconValue: 'product.colours.green',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 190,
          name: 'Black',
          colourHexValue: '#000000',
          iconValue: 'product.colours.black',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 36,
          name: 'Red',
          colourHexValue: '#FF0000',
          iconValue: 'product.colours.red',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 29,
          name: 'Multi-coloured',
          colourHexValue: 'linear-gradient(45deg, #22C1C3, #FDBB2D, #9013FE)',
          iconValue: 'product.colours.multi-coloured',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 12,
          name: 'Purple',
          colourHexValue: '#800080',
          iconValue: 'product.colours.purple',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 10,
          name: 'Beige',
          colourHexValue: '#F5F5DC',
          iconValue: 'product.colours.beige',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 8,
          name: 'Cream',
          colourHexValue: '#FFFFF0',
          iconValue: 'product.colours.cream',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 6,
          name: 'Orange',
          colourHexValue: '#FF6600',
          iconValue: 'product.colours.orange',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 6,
          name: 'White',
          colourHexValue: '#FFFFFF',
          iconValue: 'product.colours.white',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 4,
          name: 'Silver',
          colourHexValue: '#C0C0C0',
          iconValue: 'product.colours.silver',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 3,
          name: 'Yellow',
          colourHexValue: '#FFFF00',
          iconValue: 'product.colours.yellow',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
        {
          count: 2,
          name: 'Gold',
          colourHexValue: '#DAA520',
          iconValue: 'product.colours.gold',
          disabled: false,
          selected: false,
          hexColourType: true,
          hasHexCode: true,
        },
      ],
    },
    {
      id: 'Size',
      order: 3,
      data: [
        {
          name: '6',
          count: 99,
          selected: false,
          disabled: false,
        },
        {
          name: '8',
          count: 180,
          selected: false,
          disabled: false,
        },
        {
          name: '10',
          count: 183,
          selected: false,
          disabled: false,
        },
        {
          name: '12',
          count: 179,
          selected: false,
          disabled: false,
        },
        {
          name: '14',
          count: 176,
          selected: false,
          disabled: false,
        },
        {
          name: '16',
          count: 154,
          selected: false,
          disabled: false,
        },
        {
          name: '18',
          count: 140,
          selected: false,
          disabled: false,
        },
        {
          name: '20',
          count: 109,
          selected: false,
          disabled: false,
        },
        {
          name: '22',
          count: 74,
          selected: false,
          disabled: false,
        },
        {
          name: '24',
          count: 54,
          selected: false,
          disabled: false,
        },
        {
          name: '26',
          count: 14,
          selected: false,
          disabled: false,
        },
        {
          name: '34',
          count: 3,
          selected: false,
          disabled: false,
        },
        {
          name: '36',
          count: 3,
          selected: false,
          disabled: false,
        },
        {
          name: '38',
          count: 5,
          selected: false,
          disabled: false,
        },
        {
          name: '40',
          count: 5,
          selected: false,
          disabled: false,
        },
        {
          name: '42',
          count: 5,
          selected: false,
          disabled: false,
        },
        {
          name: '44',
          count: 5,
          selected: false,
          disabled: false,
        },
        {
          name: '10 Regular',
          count: 140,
          selected: false,
          disabled: false,
        },
        {
          name: '12 Regular',
          count: 137,
          selected: false,
          disabled: false,
        },
        {
          name: '14 Regular',
          count: 137,
          selected: false,
          disabled: false,
        },
        {
          name: '8 Regular',
          count: 128,
          selected: false,
          disabled: false,
        },
        {
          name: '16 Regular',
          count: 126,
          selected: false,
          disabled: false,
        },
        {
          name: '6 Long',
          count: 119,
          selected: false,
          disabled: false,
        },
        {
          name: '6 Regular',
          count: 118,
          selected: false,
          disabled: false,
        },
        {
          name: '20 Regular',
          count: 117,
          selected: false,
          disabled: false,
        },
        {
          name: '18 Regular',
          count: 115,
          selected: false,
          disabled: false,
        },
        {
          name: '8 Long',
          count: 104,
          selected: false,
          disabled: false,
        },
        {
          name: '24 Regular',
          count: 102,
          selected: false,
          disabled: false,
        },
        {
          name: '22 Regular',
          count: 97,
          selected: false,
          disabled: false,
        },
        {
          name: '12 Long',
          count: 95,
          selected: false,
          disabled: false,
        },
        {
          name: '10 Long',
          count: 92,
          selected: false,
          disabled: false,
        },
        {
          name: '16 Long',
          count: 91,
          selected: false,
          disabled: false,
        },
        {
          name: '14 Long',
          count: 88,
          selected: false,
          disabled: false,
        },
        {
          name: '20 Long',
          count: 88,
          selected: false,
          disabled: false,
        },
        {
          name: '24 Long',
          count: 85,
          selected: false,
          disabled: false,
        },
        {
          name: '22 Long',
          count: 78,
          selected: false,
          disabled: false,
        },
        {
          name: '18 Long',
          count: 75,
          selected: false,
          disabled: false,
        },
        {
          name: 'Medium',
          count: 20,
          selected: false,
          disabled: false,
        },
        {
          name: '12 Petite',
          count: 18,
          selected: false,
          disabled: false,
        },
        {
          name: '14 Petite',
          count: 18,
          selected: false,
          disabled: false,
        },
        {
          name: 'Large',
          count: 18,
          selected: false,
          disabled: false,
        },
        {
          name: '18 Petite',
          count: 17,
          selected: false,
          disabled: false,
        },
        {
          name: 'Extra Small',
          count: 17,
          selected: false,
          disabled: false,
        },
        {
          name: 'Extra Large',
          count: 16,
          selected: false,
          disabled: false,
        },
        {
          name: 'Small',
          count: 16,
          selected: false,
          disabled: false,
        },
        {
          name: '10 Petite',
          count: 15,
          selected: false,
          disabled: false,
        },
        {
          name: '16 Petite',
          count: 15,
          selected: false,
          disabled: false,
        },
        {
          name: '26-28',
          count: 15,
          selected: false,
          disabled: false,
        },
        {
          name: '6 Petite',
          count: 15,
          selected: false,
          disabled: false,
        },
        {
          name: '8 Petite',
          count: 12,
          selected: false,
          disabled: false,
        },
        {
          name: 'XX Large',
          count: 12,
          selected: false,
          disabled: false,
        },
        {
          name: '14 Short',
          count: 10,
          selected: false,
          disabled: false,
        },
        {
          name: '20 Short',
          count: 9,
          selected: false,
          disabled: false,
        },
        {
          name: '22 Short',
          count: 9,
          selected: false,
          disabled: false,
        },
        {
          name: '12 Short',
          count: 8,
          selected: false,
          disabled: false,
        },
        {
          name: '16 Short',
          count: 8,
          selected: false,
          disabled: false,
        },
        {
          name: '18 Short',
          count: 8,
          selected: false,
          disabled: false,
        },
        {
          name: '20 Petite',
          count: 8,
          selected: false,
          disabled: false,
        },
        {
          name: '22 Petite',
          count: 8,
          selected: false,
          disabled: false,
        },
        {
          name: '24 Short',
          count: 8,
          selected: false,
          disabled: false,
        },
        {
          name: '10 Short',
          count: 7,
          selected: false,
          disabled: false,
        },
        {
          name: '24 Petite',
          count: 6,
          selected: false,
          disabled: false,
        },
        {
          name: '6 Short',
          count: 6,
          selected: false,
          disabled: false,
        },
        {
          name: '8 Short',
          count: 6,
          selected: false,
          disabled: false,
        },
      ],
    },
    {
      id: 'Product Type',
      order: 4,
      data: [
        {
          name: 'Dresses',
          count: 476,
          selected: false,
          disabled: false,
        },
        {
          name: 'Jumpsuits',
          count: 15,
          selected: false,
          disabled: false,
        },
        {
          name: 'Dungarees',
          count: 4,
          selected: false,
          disabled: false,
        },
        {
          name: 'Pinafores',
          count: 3,
          selected: false,
          disabled: false,
        },
        {
          name: 'Skirts',
          count: 2,
          selected: false,
          disabled: false,
        },
      ],
    },
  ],
  pagination: { totalItems: 10 },
};

export const mockProducts: ProductSearchResponse = {
  products: [
    {
      id: '60529550',
      productId: '60529550',
      title: 'V-Neck Knee Length Swing Dress',
      url: 'v-neck-knee-length-smock-dress/p/clp60529552?color=BLACK&image=SD_10_T97_6310B_Y0_X_EC_90',
      price: '£125.00',
      brand: 'JAEGER',
      isInStock: true,
      imageUrl: ['SD_10_T97_6310B_KH_X_EC_0', 'SD_10_T97_6310B_KH_X_EC_0'],
      metadata: {
        isPinned: false,
        isBoosted: true,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60529551',
      productId: '60529551',
      title: 'V-Neck Knee Length Swing Dress',
      url: 'v-neck-knee-length-smock-dress/p/clp60529552?color=KHAKI&image=SD_10_T97_6310B_KH_X_EC_90',
      price: '£125.00',
      brand: 'JAEGER',
      isInStock: false,
      imageUrl: [
        'SD_10_T97_6310B_KH_X_EC_0',
        'SD_10_T97_6310B_KH_X_EC_0',
        'SD_10_T97_6310B_KH_X_EC_90',
        'SD_10_T97_6310B_KH_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '22531022',
      productId: '22531022',
      title: 'Swing Dress',
      url: 'swing-dress/p/clp22531022?color=BLACKMIX&image=SD_10_T83_5439_Y4_X_EC_90',
      price: '£89.00',
      brand: 'Phase Eight',
      isInStock: true,
      imageUrl: [
        'SD_10_T83_5439_Y4_X_EC_90',
        'SD_10_T83_5439_Y4_X_EC_90',
        'SD_10_T83_5439_Y4_X_EC_90',
        'SD_10_T83_5439_Y4_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '22530754',
      productId: '22530754',
      title: 'Cord Shirt Dress',
      url: 'cord-shirt-dress/p/clp22530754?color=PINK&image=SD_10_T83_5732_A0_X_EC_90',
      price: '£59.50',
      brand: 'FatFace',
      isInStock: true,
      imageUrl: [
        'SD_10_T83_5732_A0_X_EC_0',
        'SD_10_T83_5732_A0_X_EC_0',
        'SD_10_T83_5732_A0_X_EC_90',
        'SD_10_T83_5732_A0_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60534443',
      productId: '60534443',
      title: 'Shirred Midi Smock Dress',
      url: 'shirred-midi-smock-dress/p/clp60534443?color=BLACK&image=SD_01_T69_1196_Y0_X_EC_90',
      price: '£45.00',
      brand: 'M&S Collection',
      isInStock: true,
      imageUrl: [
        'SD_01_T69_1196_Y0_X_EC_0',
        'SD_01_T69_1196_Y0_X_EC_0',
        'SD_01_T69_1196_Y0_X_EC_90',
        'SD_01_T69_1196_Y0_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60506901',
      productId: '60506901',
      title: 'Floral Midi Waisted Dress',
      url: 'floral-midi-waisted-dress/p/clp60506901?color=NAVYMIX&image=SD_01_T42_4755_F4_X_EC_90',
      price: '£39.50',
      brand: 'M&S Collection',
      isInStock: true,
      imageUrl: [
        'SD_01_T42_4755_F4_X_EC_0',
        'SD_01_T42_4755_F4_X_EC_0',
        'SD_01_T42_4755_F4_X_EC_90',
        'SD_01_T42_4755_F4_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60533510',
      productId: 'P60533510',
      title: 'Floral Midi Waisted Dress',
      url: 'floral-midi-waisted-dress/p/clp60533510?color=BLUEMIX&image=SD_01_T69_1192_E4_X_EC_90',
      price: '£45.00',
      brand: 'M&S Collection',
      isInStock: true,
      imageUrl: [
        'SD_01_T69_1192_E4_X_EC_0',
        'SD_01_T69_1192_E4_X_EC_0',
        'SD_01_T69_1192_E4_X_EC_90',
        'SD_01_T69_1192_E4_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60534411',
      productId: 'P60533510',
      title: 'Floral Midi Waisted Dress',
      url: 'floral-midi-waisted-dress/p/clp60533510?color=MULTI&image=SD_01_T69_1192_ZZ_X_EC_90',
      price: '£45.00',
      brand: 'M&S Collection',
      isInStock: true,
      imageUrl: [
        'SD_01_T69_1192_ZZ_X_EC_0',
        'SD_01_T69_1192_ZZ_X_EC_0',
        'SD_01_T69_1192_ZZ_X_EC_90',
        'SD_01_T69_1192_ZZ_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '60530380',
      productId: 'P60530380',
      title: 'Satin Midi Tea Dress',
      url: 'satin-midi-tea-dress/p/clp60530380?color=OLIVE&image=SD_01_T69_6085_JR_X_EC_90',
      price: '£79.00',
      brand: 'M&S X GHOST',
      isInStock: true,
      imageUrl: [
        'SD_01_T69_6085_JR_X_EC_0',
        'SD_01_T69_6085_JR_X_EC_0',
        'SD_01_T69_6085_JR_X_EC_90',
        'SD_01_T69_6085_JR_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '22532311',
      productId: '22532311',
      title: 'Sequin Mini Shift Dress',
      url: 'sequin-mini-shift-dress/p/clp22532311?color=BLACKMIX&image=SD_10_T83_3103_Y4_X_EC_90',
      price: '£149.00',
      brand: 'HOBBS',
      isInStock: true,
      imageUrl: [
        'SD_10_T83_3103_Y4_X_EC_0',
        'SD_10_T83_3103_Y4_X_EC_0',
        'SD_10_T83_3103_Y4_X_EC_90',
        'SD_10_T83_3103_Y4_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '22532683',
      productId: 'P22532683',
      title: 'Ditsy Floral Shirt Dress',
      url: 'ditsy-floral-shirt-dress/p/clp22532683?color=GREYMIX&image=SD_10_T83_8880_T4_X_EC_90',
      price: '£59.00',
      brand: 'White Stuff',
      isInStock: true,
      imageUrl: [
        'SD_10_T83_8880_T4_X_EC_0',
        'SD_10_T83_8880_T4_X_EC_0',
        'SD_10_T83_8880_T4_X_EC_90',
        'SD_10_T83_8880_T4_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
    {
      id: '22531286',
      productId: '22531286',
      title: 'Floral Midi Waisted Dress',
      url: 'cotton-floral-midi-waisted-dress/p/clp22531286?color=NAVYMIX&image=SD_10_T83_6647_F4_X_EC_90',
      price: '£55.00',
      brand: 'White Stuff',
      isInStock: true,
      imageUrl: [
        'SD_10_T83_6647_F4_X_EC_0',
        'SD_10_T83_6647_F4_X_EC_0',
        'SD_10_T83_6647_F4_X_EC_90',
        'SD_10_T83_6647_F4_X_EC_90',
      ],
      metadata: {
        isPinned: false,
        isBoosted: false,
        isBuried: false,
        isBlocked: false,
      },
    },
  ],
  pagination: { totalItems: 130 },
};

export const mockFacets: BetaMerchandisingFacetListData = {
  facets: [
    {
      id: 'a43271cf-bf57-4e40-8fe3-f3d59f9c4c2e',
      indexPropertyName: 'categoryId',
      displayValue: 'Categories',
      lastChanged: { date: '2024-08-15T10:31:27Z', user: 'James Winfield' },
      excludedValues: [],
      boosted: [],
      merged: [],
    },
    {
      id: '513a0da0-3eb0-11ef-9a6a-000000000000',
      indexPropertyName: 'homeCollection',
      displayValue: 'Collections',
      lastChanged: { date: '2024-08-15T10:31:08Z', user: 'James Winfield' },
      excludedValues: [],
      boosted: [],
      merged: [],
    },
    {
      id: '528e50d2-5f32-4248-868b-72cdce842597',
      indexPropertyName: 'colourGroup',
      displayValue: 'Colour',
      lastChanged: { date: '2024-09-09T12:18:42Z', user: 'James Winfield' },
      excludedValues: ['Brown'],
      boosted: ['Pink', 'Navy', 'Grey', 'Blue', 'Green'],
      merged: [],
    },
    {
      id: '4f8d4802-3eb0-11ef-9a6a-000000000000',
      indexPropertyName: 'colourGroup',
      displayValue: 'Colourgroup',
      lastChanged: { date: '2024-08-15T10:31:08Z', user: 'James Winfield' },
      excludedValues: [],
      boosted: [],
      merged: [],
    },
    {
      id: '4f8d4803-3eb0-11ef-9a6a-000000000000',
      indexPropertyName: 'colour',
      displayValue: 'Colours',
      lastChanged: { date: '2024-08-27T11:17:51Z', user: 'Graham Licence' },
      excludedValues: ['BLUE MIX', 'NAVY MIX', 'IVORY MIX'],
      boosted: ['NAVY', 'BLACK MIX', 'GREY', 'PINK', 'RED'],
      merged: [],
    },
    {
      id: '1e404940-3240-11ef-aa09-000000000000',
      indexPropertyName: 'styles',
      displayValue: 'Style',
      lastChanged: { date: '2024-08-15T10:31:07Z', user: 'James Winfield' },
      excludedValues: ['Ties'],
      boosted: [],
      merged: [],
    },
  ],
};

export const mockAttributeValue: AttributeValuesResponse = {
  values: [
    { displayValue: 'CHAMPAGNE' },
    { displayValue: 'NO COLOUR' },
    { displayValue: 'SMOKE' },
  ],
  pagination: { totalItems: 3 },
};

export const mockCategoryNumericAttributes: AttributesResponse = {
  attributes: [
    {
      name: 'predictions.salesIn1Day.normalisedValue',
      type: 'numeric',
    },
    {
      name: 'newInFreshNess',
      type: 'numeric',
    },
  ],
};

export const mockCategoryAlphanumericAttributes: AttributesResponse = {
  attributes: [
    {
      name: 'offerFlag',
      type: 'alphanumeric',
      values: [
        {
          value: '0',
        },
        {
          value: '1',
        },
      ],
    },
    {
      name: 'fit',
      type: 'alphanumeric',
      values: [
        {
          value: 'Regular fit',
        },
        {
          value: 'Relaxed fit',
        },
        {
          value: 'Fitted',
        },
        {
          value: 'Straight leg',
        },
      ],
    },
  ],
};
