name: Action Prepare
description: Sets up node
runs:
  using: composite
  steps:
    - name: Get versions from package.json
      id: get-versions-from-package-json
      shell: bash
      run: |
        set -x
        NODE_VERSION=$(jq -r '.engines.node' < package.json)
        echo "node-version=${NODE_VERSION}" >> "$GITHUB_OUTPUT"

    - name: Install pnpm
      uses: pnpm/action-setup@v6

    - name: Set up node
      uses: actions/setup-node@v7.0.0
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: '10'
      with:
        node-version: ${{ steps.get-versions-from-package-json.outputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
