runs:
  using: composite
  steps:
    - name: Get versions from package.json
      id: get-versions-from-package-json
      shell: bash
      run: |
        set -x
        NODE_VERSION=$(jq -r '.engines.node' < package.json)
        echo "node-version=${NODE_VERSION}" >> "$GITHUB_OUTPUT"

    - uses: actions/setup-node@v4.0.2
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: '10'
      with:
        node-version: ${{ steps.get-versions-from-package-json.outputs.node-version }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm install --frozen-lockfile --ignore-scripts
