name: pr-env-close

env:
  GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
  BRIGHTCLOUD_REF: main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  pull_request:
    types: [closed]

jobs:
  check-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check composite parameter for the reusable pipeline
        id: check-composite-vars
        uses: DigitalInnovation/brightcloud/.github/actions/check-layer-runtime-type@feat/oidcn
    outputs:
      oidc: ${{ steps.check-composite-vars.outputs.oidc}}

  kill-pr-env:
    runs-on: ubuntu-latest
    environment:
      name: deveun
    needs:
      - check-vars
    name: pr-close-destroy-env
    steps:
      - name: Checkout-local-repo
        uses: actions/checkout@v3
      - id: dynamic-env-name
        uses: DigitalInnovation/brightcloud/.github/actions/get-app-name@feat/oidcn
      - id: dynamic-env-destroy-oidc
        if: ${{ needs.check-vars.outputs.oidc == 'true' }}
        uses: DigitalInnovation/brightcloud/.github/actions/webapp-dynamic-env-housekeeping-oidc@feat/oidcn
        with:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          SAML_GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
          DYNAMIC_ENV_APP_NAME: ${{ steps.dynamic-env-name.outputs.dynamic-env-name }}
          BRIGHTCLOUD_REF: ${{ env.BRIGHTCLOUD_REF }}
      - id: dynamic-env-destroy
        if: ${{ needs.check-vars.outputs.oidc != 'true' }}
        uses: DigitalInnovation/brightcloud/.github/actions/webapp-dynamic-env-housekeeping@main
        with:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          SP_PASSWORD: ${{ secrets.SP_PASSWORD }}
          SAML_GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
          DYNAMIC_ENV_APP_NAME: ${{ steps.dynamic-env-name.outputs.dynamic-env-name }}
          BRIGHTCLOUD_REF: ${{ env.BRIGHTCLOUD_REF }}
