name: repo-init
on: 
  workflow_dispatch:
    inputs:
      APP_NAME:
        description: 'application name to be used across the brightcloud stack'     
        required: false
        default: 'changeme'


jobs:
  bootstrap-repository:
    runs-on: ubuntu-latest
    name: repo-init
    env:
      GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
      GITHUB_WORKSPACE: ${{ github.workspace }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      APP_NAME: ${{ github.event.inputs.APP_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          repository: DigitalInnovation/brightcloud
          token: ${{ secrets.SAML_GITHUB_TOKEN }}
          ref: feat/oidcn
          path: brightcloud
      - name: debug
        run: |
          ${{ github.workspace }}/brightcloud/.github/scripts/repo-bootstrapper.sh -a repo_init
          rm -rf ${{ github.workspace }}/brightcloud
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.1
        with: 
          token: ${{secrets.SAML_GITHUB_TOKEN }}
          branch: bootstrap
          branch-suffix: random
          commit-message: "feat: bootstrapping repo run ${{ github.run_id }}"
          title: "automated-repo-bootstrap-runid-${{ github.run_id }}"
          labels: |
            repo-init
