name: bc-tf-webapp-stack
on:
  pull_request:
    paths:
      - ".github/workflows/brightcloud-call-tf-webapp-stack.yml"
      - "ci/infra/terraform/vars/common.tfvars"
      - "ci/infra/terraform/layer-1-network-security/**"
      - "ci/infra/terraform/layer-2-data/**"
      - "ci/infra/terraform/layer-3-app/**"
      - "ci/infra/terraform/layer-3-container/**"
      - "ci/infra/terraform/layer-4-edge/**"
      - "ci/infra/terraform/vars/**"

  push:
    branches:
      - main
    paths:
      - ".github/workflows/brightcloud-call-tf-webapp-stack.yml"
      - "ci/infra/terraform/vars/common.tfvars"
      - "ci/infra/terraform/layer-1-network-security/**"
      - "ci/infra/terraform/layer-2-data/**"
      - "ci/infra/terraform/layer-3-app/**"
      - "ci/infra/terraform/layer-3-container/**"
      - "ci/infra/terraform/layer-4-edge/**"
      - "ci/infra/terraform/vars/**"
env:
  VARS_BASE_PATH: "ci/infra/terraform/vars"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
# 2
jobs:
  check-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Check composite parameter for the reusable pipeline
        id : check-composite-vars
        uses: DigitalInnovation/brightcloud/.github/actions/check-layer-runtime-type@feat/oidcn
    outputs:
      linux-fx-version: ${{ steps.check-composite-vars.outputs.linux-fx-version }}

  call-tf-webapp-stack-oidc:
    needs:
      - check-vars
    if: ${{ needs.check-vars.outputs.linux-fx-version != 'docker' }}
    uses: DigitalInnovation/brightcloud/.github/workflows/tf-webapp-stack-oidc.yml@feat/oidcn
    with:
      TRIGGER_EVENT: ${{ github.event_name }}
      BRIGHTCLOUD_REF: feat/oidcn
    secrets:
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
      SAML_GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
      BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
      ALL_SECRETS: ('${{ toJSON(secrets) }}')

  call-tf-webapp-container-stack-oidc:
    needs:
      - check-vars
    if: ${{ needs.check-vars.outputs.linux-fx-version == 'docker' }}
    uses: DigitalInnovation/brightcloud/.github/workflows/tf-webapp-container-stack-oidc.yml@feat/oidcn
    with:
      TRIGGER_EVENT: ${{ github.event_name }}
      BRIGHTCLOUD_REF: feat/oidcn
    secrets:
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
      SAML_GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
      BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
      ALL_SECRETS: ('${{ toJSON(secrets) }}')
