name: bc-doc-quality-check

on:
  pull_request:
    paths:
      - docs/**
      - "**.md"

jobs:
  misspell:
    runs-on: ubuntu-latest
    name: Check spelling
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: reviewdog/action-misspell@v1.12.3
        with:
          github_token: ${{ secrets.github_token }}

  writing-quality:
    runs-on: ubuntu-latest
    name: Check writing standards
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: tsuyoshicho/action-redpen@v1.11.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          basedir: "docs"
          targets: "*.md"

  # megalinter-docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #     name: Checkout source code
  #   - name: MegaLinter-tf
  #     id: ml
  #     uses: megalinter/megalinter/flavors/documentation@v5
  #     env:
  #       VALIDATE_ALL_CODEBASE: true
  #       PRINT_ALPACA: false
  #       GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
  #       ENABLE_LINTERS: MARKDOWN_MARKDOWN_TABLE_FORMATTER,MARKDOWN_MARKDOWN_LINK_CHECK,MARKDOWN_REMARK_LINT,MARKDOWN_MARKDOWNLINT
