
name: bc-version-check

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'
  workflow_dispatch:
  
jobs:
  pull:
    runs-on: ubuntu-latest
    name: Run Dependency check
    env:
      GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
      GITHUB_WORKSPACE: ${{ github.workspace }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      APP_NAME: bc-test01-mock
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: DigitalInnovation/brightcloud
          token: ${{ secrets.SAML_GITHUB_TOKEN }}
          ref: feat/oidcn
          path: brightcloud
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: DigitalInnovation/brightcloud-template-deployment
          token: ${{ secrets.SAML_GITHUB_TOKEN }}
          ref: main
          path: brightcloud-template-deployment
      - name: debug
        run: |
          ${{ github.workspace }}/brightcloud/.github/scripts/repo-bootstrapper.sh -a brightcloud_update
          cp -rf ${{ github.workspace }}/brightcloud-template-deployment/.github/workflows/repo-init.yml ${{ github.workspace }}/.github/workflows/brightcloud-repo-init.yml
          rm -rf ${{ github.workspace }}/brightcloud
          rm -rf ${{ github.workspace }}/brightcloud-template-deployment
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          token: ${{secrets.SAML_GITHUB_TOKEN }}
          branch: brightcloud-version-update
          commit-message: "feat: brightcloud version update run ${{ github.run_id }}"
          title: "automated-brightcloud-version-update-runid-${{ github.run_id }}"
          labels: |
            brightcloud-update
            version-check
