name: bc-tf-dynatrace
on:
  pull_request:
    paths:
      - '.github/workflows/call-tf-dynatrace-stack.yml'
      - 'ci/infra/terraform/dynatrace/non-production/**'
      - 'ci/infra/terraform/dynatrace/production/**'

  push:
    branches:
      - main
    paths:
      - '.github/workflows/call-tf-dynatrace-stack.yml'
      - 'ci/infra/terraform/dynatrace/non-production/**'
      - 'ci/infra/terraform/dynatrace/production/**'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  check-vars:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    outputs:
      oidc: ${{ steps.check-oidc.outputs.oidc }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Fetch use_oidc value
        shell: bash
        id: check-oidc
        run: |
          OIDC=$(grep 'use_oidc' "${GITHUB_WORKSPACE}/ci/infra/terraform/vars/common.tfvars" | grep "=" | cut -d '"' -f 2 | awk -F= '{print tolower($1)}' | sed -e 's/^[[:space:],"]*//' -e 's/[[:space:],"]*$//')
          if [ "$OIDC" != "true" ]; then
            echo "OIDC is not enabled."
            echo "Please configure federated credentials for your service principal. Using a service principal password is no longer supported"
            exit 1
          else
            echo "OIDC enabled"
          fi

  upload-files:
    needs:
      - check-vars
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Upload Nonprod Dashboard Files (if exists)
        uses: actions/upload-artifact@v7
        with:
          name: nonprod_dashboard_files
          path: ci/infra/terraform/dynatrace/non-production/dashboard/
          if-no-files-found: ignore

      - name: Upload Prod Dashboard Files (if exists)
        uses: actions/upload-artifact@v7
        with:
          name: prod_dashboard_files
          path: ci/infra/terraform/dynatrace/production/dashboard/
          if-no-files-found: ignore

  call-tf-plan-dynatrace_stack-oidc:
    name: Call TF Plan
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    needs:
      - check-vars
      - upload-files
    if: ${{ needs.check-vars.outputs.oidc == 'true' }}
    uses: DigitalInnovation/Dynatrace/.github/workflows/tf-dynatrace-stack-oidc.yml@v2
    with:
      TRIGGER_EVENT: ${{ github.event_name }}
      DYNATRACE_REF: v2
    secrets:
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
      SAML_GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
      BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
      PAGERDUTY_TOKEN: ${{ secrets.PAGERDUTY_DYNATRACE_API_KEY }}
      _DYNATRACE_ACCESS_TOKEN: ${{ secrets._DYNATRACE_ACCESS_TOKEN }}
      _DYNATRACE_ENV_URL: ${{ secrets._DYNATRACE_ENV_URL }}
      DYNATRACE_IAM_CLIENT_ID: ${{ secrets.DYNATRACE_IAM_CLIENT_ID }}
      DYNATRACE_IAM_CLIENT_SECRET: ${{ secrets.DYNATRACE_IAM_CLIENT_SECRET }}
      DYNATRACE_IAM_ACCOUNT_ID: ${{ secrets.DYNATRACE_IAM_ACCOUNT_ID }}
      TEAMS_WORKFLOW_WEBHOOK_URL: ${{ secrets.TEAMS_WORKFLOW_WEBHOOK_URL }}
