#This is an initialization workflow for copying Node starter workflow and sample app (if required)
name: devsecops-init-unified-pipeline-GH-AZ

on: 
  workflow_dispatch:
    inputs:
      CICD_TOOL:
        type: choice
        description: 'Type cicd pipeline tool used'     
        required: true
        options: 
        - Github-Actions
        - Azure-Devops
        default: 'Github-Actions'
        
      STACK_NAME:
        type: choice
        description: 'Type in Java or Node'     
        required: true
        options: 
        - Node
        - Java-maven
        - Java-gradle
        default: 'Node'
      
      INCLUDE_SAMPLE_SRC:
        type: choice
        description: 'Do you need the sample source code to be included'     
        required: false
        options: 
        - 'false'
        - 'true'
        default: 'false'
        

jobs:
  bootstrap-githubactions-repository:
    runs-on: ubuntu-latest
    name: devsecops-init
    env:
      SAML_GITHUB_TOKEN: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }}
      GITHUB_WORKSPACE: ${{ github.workspace }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      STACK: ${{ github.event.inputs.STACK_NAME }}
      CICDTOOL: ${{ github.event.inputs.CICD_TOOL }}
      SRC_FLAG: ${{github.event.inputs.INCLUDE_SAMPLE_SRC }}
      
    if: ${{ github.event.inputs.CICD_TOOL == 'Github-Actions' }}  
    
    permissions:
      contents: write
      pull-requests: write 
    
    steps:
      - name: Pre-check
        run: |
          echo STACK: ${{ env.STACK }}  ${{ github.event.inputs.STACK_NAME }}
          echo CICD: ${{ env.CICDTOOL }} ${{github.event.inputs.CICD_TOOL }}
          echo FALG: ${{ env.SRC_FLAG }} ${{github.event.inputs.INCLUDE_SAMPLE_SRC }}
          
                    
######   Checkout repositories  #######    
      - name: Checkout repo
        uses: actions/checkout@v3.1.0
#         with:
#           repository: DigitalInnovation/${{env.APP_NAME}}
#           token: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }} 
#           ref: refs/heads/main          
        
      - name: Checkout Java starter repo
        uses: actions/checkout@v3.1.0
        with:
          repository: DigitalInnovation/Cloud-DevSecOps-Pipeline-Java
          token: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }} 
          ref: refs/heads/main
          path: devsecops-starter
        if: ${{ ( env.STACK == 'Java-maven' ||  env.STACK == 'Java-gradle' ) }}
        
      - name: Checkout Node starter repo
        uses: actions/checkout@v3.1.0
        with:
          repository: DigitalInnovation/Cloud-DevSecOps-Pipeline-Node
          token: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }}  
          ref: refs/heads/main
          path: devsecops-starter
        if: ${{ env.STACK == 'Node' }}

######   ADD NECESSARY PIPELINE CONTENT  #######
      - name: Add necessary JAVA-MAVEN STARTER PIPELINE Workflows
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          
          mkdir -p ${REPO_PATH}/.github/workflows
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/java-maven_starter_pipeline.yml ${REPO_PATH}/.github/workflows/java-maven_starter_pipeline.yml
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/pipeline_insights.yml ${REPO_PATH}/.github/workflows/pipeline_insights.yml
        if: ${{ env.STACK == 'Java-maven' }}
        
      - name: Add necessary JAVA-GRADLE STARTER PIPELINE Workflows
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          
          mkdir -p ${REPO_PATH}/.github/workflows
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/java-gradle_starter_pipeline.yml ${REPO_PATH}/.github/workflows/java-gradle_starter_pipeline.yml
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/pipeline_insights.yml ${REPO_PATH}/.github/workflows/pipeline_insights.yml
        if: ${{ env.STACK == 'Java-gradle' }}  
        
      - name: Add necessary NODE STARTER PIPELINE Workflows 
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          mkdir -p ${REPO_PATH}/.github/workflows
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/npm_build_starter_pipeline.yml ${REPO_PATH}/.github/workflows/npm_build_starter_pipeline.yml
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/workflows/pipeline_insights.yml ${REPO_PATH}/.github/workflows/pipeline_insights.yml
        if: ${{ env.STACK == 'Node' }}
        

######   ADD SAMPLE CONTENT  #######

      - name: Add optional JAVA-MAVEM Sample Source Content 
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/java-maven-sample/* ${REPO_PATH}
        if: ${{ env.SRC_FLAG == 'true' && env.STACK == 'Java-maven'}}
        
      - name: Add optional JAVA-GRADLE Sample Source Content 
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/java-gradle-sample/* ${REPO_PATH}
        if: ${{ env.SRC_FLAG == 'true' && env.STACK == 'Java-gradle'}}   
        
      - name: Add optional Node Sample Source Content 
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          cp -rf ${STARTER_REPO_WORKFLOW_PATH}/nodejs-sample/* ${REPO_PATH}
        if: ${{ env.SRC_FLAG == 'true' && env.STACK == 'Node'}}
        
######   CLEAN UP POST PROCESSS and CREATE PULL REQUEST #######          
      - name: remove the Starter Repo Local Clone
        run: |
          rm -rf ${{ github.workspace }}/devsecops-starter
           
        
      - name: Create Pull Request to add Starter Pipeline and sample source to build.
        uses: peter-evans/create-pull-request@v5.0.2
        with: 
          token: ${{secrets.DEVSECOPS_STARTER_INIT_PAT}} 
          branch: devsecops-bootstrap
          branch-suffix: random
          commit-message: "feat: bootstrapping repo run ${{ github.run_id }}"
          title: "automated-devsecops-repo-bootstrap-runid-${{ github.run_id }}"
          labels: |
            devsecops-init-starter-piepline-src          
   
########################################################################################################################### 
 
 
####   Bootstract Script to setup repostiory using github actions workflow          
  bootstrap-azuredevops-repository:
    runs-on: ubuntu-latest
    name: devsecops-azure-init
    env:
      SAML_GITHUB_TOKEN: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }}
      GITHUB_WORKSPACE: ${{ github.workspace }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      STACK: ${{ github.event.inputs.STACK_NAME }}
      CICDTOOL: ${{ github.event.inputs.CICD_TOOL }}
      SRC_FLAG: ${{github.event.inputs.INCLUDE_SAMPLE_SRC }}
    if: ${{ needs.read_process_inputs.outputs.CICD_TOOL == 'Azure-Devops' }}  
    permissions:
      contents: write
      pull-requests: write 
    
    steps:
      - name: Pre-check
        run: |
          echo STACK: ${{ env.STACK }}  ${{ needs.read_process_inputs.outputs.STACK_NAME }}
          echo CICD: ${{ env.CICDTOOL }} ${{needs.read_process_inputs.outputs.CICD_TOOL }}
          echo FALG: ${{ env.SRC_FLAG }} ${{needs.read_process_inputs.outputs.INCLUDE_SAMPLE_SRC }}
          
                    
######   Checkout repositories  #######    
      - name: Checkout repo
        uses: actions/checkout@v3.1.0
#         with:
#           repository: DigitalInnovation/${{env.APP_NAME}}
#           token: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }} 
#           ref: refs/heads/main  
        
      - name: Checkout Java-Maven starter repo
        uses: actions/checkout@v3.1.0
        with:
          repository: DigitalInnovation/Cloud-DevSecOps-AZD-Pipeline-Java-Maven
          token: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }} 
          ref: refs/heads/main
          path: devsecops-starter
        if: ${{ env.STACK == 'Java-maven'}}
        
      - name: Checkout Java-Gradle starter repo
        uses: actions/checkout@v3.1.0
        with:
          repository: DigitalInnovation/Cloud-DevSecOps-AZD-Pipeline-Java-Gradle
          token: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }} 
          ref: refs/heads/main
          path: devsecops-starter
        if: ${{ env.STACK == 'Java-gradle' }}  
        
      - name: Checkout Node starter repo
        uses: actions/checkout@v3.1.0
        with:
          repository: DigitalInnovation/Cloud-DevSecOps-AZD-Pipeline-Node
          token: ${{ secrets.DEVSECOPS_STARTER_INIT_PAT }}  
          ref: refs/heads/main
          path: devsecops-starter
        if: ${{ env.STACK == 'Node' }}

      - name: remove uneeded files from starter repo
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          rm ${STARTER_REPO_PATH}/README.md
          rm ${STARTER_REPO_PATH}/mkdocs.yml
          rm ${STARTER_REPO_PATH}/catalog-info.yaml
          rm -rf ${STARTER_REPO_PATH}/Images
          rm -rf ${STARTER_REPO_PATH}/docs
       

######   ADD NECESSARY PIPELINE CONTENT  #######
      - name: Add AZURE STARTER PIPELINE Workflows for the stack
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          mkdir -p ${REPO_PATH}/.github/workflows
          cp -rf ${STARTER_REPO_PATH}/azure-pipelines.yml ${REPO_PATH}/azure-pipelines.yml
          
######   ADD SAMPLE CONTENT  #######
      - name: Adding optional Sample Source Content if requested for the stack
        run: |
          STARTER_REPO_PATH="$GITHUB_WORKSPACE/devsecops-starter"
          STARTER_REPO_WORKFLOW_PATH="${STARTER_REPO_PATH}/.github"
          REPO_PATH=$GITHUB_WORKSPACE
          cp -rf ${STARTER_REPO_PATH}/* ${REPO_PATH}
        if: ${{ env.SRC_FLAG == 'true'}}
        
        
######   CLEAN UP POST PROCESSS and CREATE PULL REQUEST #######          
      - name: remove the Starter Repo Local Clone
        run: |
          rm -rf ${{ github.workspace }}/devsecops-starter
          git status
                      
      - name: Create Pull Request to add Starter Pipeline and sample source to build.
        uses: peter-evans/create-pull-request@v5.0.2
        with: 
          token: ${{secrets.DEVSECOPS_STARTER_INIT_PAT}} 
          branch: devsecops-bootstrap
          branch-suffix: random
          commit-message: "feat: bootstrapping repo run ${{ github.run_id }}"
          title: "automated-devsecops-repo-bootstrap-runid-${{ github.run_id }}"
          labels: |
            devsecops-init-starter-piepline-src
