name: Hotfix Release

on:
  push:
    branches:
      - hotfix
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Prepare node and install dependencies
        uses: ./.github/actions/prepare

      - name: add version.txt
        run: |
          set -x
          SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
          APP_VERSION=${SHORT_COMMIT_SHA}-${{ github.run_number }}
          echo "${APP_VERSION}" > ./public/version.txt
          ls -lA

      - name: Build
        run: |
          set -x
          echo "node version: $(node --version)"
          NEXT_TELEMETRY_DISABLED=1 pnpm run build
        env:
          DYNATRACE_RUM_SCRIPT_URL_DEV: ${{ secrets.DYNATRACE_RUM_SCRIPT_URL_DEV }}
          DYNATRACE_RUM_SCRIPT_URL_PROD: ${{ secrets.DYNATRACE_RUM_SCRIPT_URL_PROD }}
          CLARITY_KEY: ${{ secrets.CLARITY_KEY }}

      - name: Validate standalone output
        run: |
          set -euxo pipefail
          ls -la .next/standalone
          test -f .next/standalone/server.js

      - name: Zip all files for upload between jobs
        run: |
          cd .next/standalone
          zip -qr next.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v7
        with:
          name: node-app
          path: .next/standalone/next.zip

  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build
    name: Deploy to Azure Web App (dev)
    environment:
      name: deveun
    steps:
      - uses: actions/checkout@v6
      - name: Get terraform settings
        id: get-tf-settings
        shell: bash
        run: |
          set -x
          STACK_VERSION="$(grep stack_version ./ci/infra/terraform/vars/common.tfvars | sed 's/[^0-9]*//g')"
          APP_NAME="dev-trading-hub"
          EUN_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-eun-layer3-rg"
          EUN_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-eun-layer4-rg"
          EUN_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}eunlayer4policywafpolicy"
          EUN_WAF_POLICY_NAME="${EUN_WAF_POLICY_NAME//"-"/""}"
          EUN_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-eun-layer3-app"
          EUW_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-euw-layer3-rg"
          EUW_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-euw-layer4-rg"
          EUW_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}euwlayer4policywafpolicy"
          EUW_WAF_POLICY_NAME="${EUW_WAF_POLICY_NAME//"-"/""}"
          EUW_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-euw-layer3-app"
          {
            echo "eun-resource-group-alias-layer3=${EUN_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "eun-resource-group-alias-layer4=${EUN_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "eun-waf-policy-name=${EUN_WAF_POLICY_NAME}"
            echo "eun-app-alias=${EUN_APP_ALIAS}"
            echo "euw-resource-group-alias-layer3=${EUW_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "euw-resource-group-alias-layer4=${EUW_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "euw-waf-policy-name=${EUW_WAF_POLICY_NAME}"
            echo "euw-app-alias=${EUW_APP_ALIAS}"
          } >> "$GITHUB_OUTPUT"

      - name: Login via Azure CLI
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets._AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets._AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: node-app

      - name: Set up environment variables
        uses: azure/cli@v2
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --settings \
              "MERCHANDISING_API_BASEURL=https://api-dev.marksandspencer.com/merchandising" \
              "MERCHANDISING_API_APIGEE_KEY=${{ secrets._MERCHANDISING_API_APIGEE_KEY }}" \
              "NEXTAUTH_SECRET=${{ secrets._NEXTAUTH_SECRET }}" \
              "NEXTAUTH_URL=https://dev-merchandising-hub.search.marksandspencer.app/api/auth" \
              "AZURE_AD_CLIENT_ID=${{ secrets._AZURE_AD_CLIENT_ID }}" \
              "AZURE_AD_CLIENT_SECRET=${{ secrets._AZURE_AD_CLIENT_SECRET }}" \
              "AZURE_AD_TENANT_ID=${{ secrets._AZURE_AD_TENANT_ID }}" \
              "WEBSITES_PORT=4200"
        env:
          AZURE_CORE_USE_MSAL_HTTP_CACHE: false

      - name: Deploy to Azure Web Apps
        uses: azure/cli@v2
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az webapp deploy \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --src-path ./next.zip \
              --type zip \
              --async true

      - name: Validate deployment
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_seconds: 20
          max_attempts: 15
          retry_wait_seconds: 10
          command: |
            set -x
            SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
            VERSION_CHECK_URL="https://dev-merchandising-hub.search.marksandspencer.app/version.txt"
            VERSION=$(curl -sf "${VERSION_CHECK_URL}")
            echo "Deployed version: ${VERSION}"
            echo ${VERSION} | grep ${SHORT_COMMIT_SHA}

      - name: Delete zip file
        run: rm next.zip

  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [build, deploy-dev]
    name: Deploy to Azure Web App (production)
    environment:
      name: prodeun
    steps:
      - uses: actions/checkout@v6
      - name: Get terraform settings
        id: get-tf-settings
        shell: bash
        run: |
          set -x
          STACK_VERSION="$(grep stack_version ./ci/infra/terraform/vars/common.tfvars | sed 's/[^0-9]*//g')"
          APP_NAME="prod-trading-hub"
          EUN_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-eun-layer3-rg"
          EUN_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-eun-layer4-rg"
          EUN_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}eunlayer4policywafpolicy"
          EUN_WAF_POLICY_NAME="${EUN_WAF_POLICY_NAME//"-"/""}"
          EUN_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-eun-layer3-app"
          EUW_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-euw-layer3-rg"
          EUW_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-euw-layer4-rg"
          EUW_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}euwlayer4policywafpolicy"
          EUW_WAF_POLICY_NAME="${EUW_WAF_POLICY_NAME//"-"/""}"
          EUW_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-euw-layer3-app"
          {
            echo "eun-resource-group-alias-layer3=${EUN_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "eun-resource-group-alias-layer4=${EUN_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "eun-waf-policy-name=${EUN_WAF_POLICY_NAME}"
            echo "eun-app-alias=${EUN_APP_ALIAS}"
            echo "euw-resource-group-alias-layer3=${EUW_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "euw-resource-group-alias-layer4=${EUW_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "euw-waf-policy-name=${EUW_WAF_POLICY_NAME}"
            echo "euw-app-alias=${EUW_APP_ALIAS}"
          } >> "$GITHUB_OUTPUT"

      - name: Login via Azure CLI
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets._AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets._AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: node-app

      - name: Set up environment variables
        uses: azure/cli@v2
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --settings \
              "MERCHANDISING_API_BASEURL=https://api.marksandspencer.com/merchandising" \
              "MERCHANDISING_API_APIGEE_KEY=${{ secrets._MERCHANDISING_API_APIGEE_KEY }}" \
              "NEXTAUTH_SECRET=${{ secrets._NEXTAUTH_SECRET }}" \
              "NEXTAUTH_URL=https://merchandising-hub.search.marksandspencer.app/api/auth" \
              "AZURE_AD_CLIENT_ID=${{ secrets._AZURE_AD_CLIENT_ID }}" \
              "AZURE_AD_CLIENT_SECRET=${{ secrets._AZURE_AD_CLIENT_SECRET }}" \
              "AZURE_AD_TENANT_ID=${{ secrets._AZURE_AD_TENANT_ID }}" \
              "CLARITY_KEY=${{ secrets.CLARITY_KEY }}" \
              "WEBSITES_PORT=4200"
        env:
          AZURE_CORE_USE_MSAL_HTTP_CACHE: false

      - name: Deploy to Azure Web Apps slot
        uses: azure/cli@v2
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az webapp deploy \
            --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
            --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
            --slot preprod \
            --src-path ./next.zip \
            --type zip \
            --async true
        env:
          AZURE_CORE_USE_MSAL_HTTP_CACHE: false

      - name: Validate version number
        uses: nick-fields/retry@v3.0.2
        with:
          timeout_seconds: 20
          max_attempts: 10
          retry_wait_seconds: 10
          command: |
            set -x
            SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
            VERSION_CHECK_URL="https://stage-merchandising-hub.search.marksandspencer.app/version.txt"
            VERSION=$(curl "${VERSION_CHECK_URL}")
            APP_COMMIT_SHA=${SHORT_COMMIT_SHA}
            echo ${VERSION} | grep ${APP_COMMIT_SHA}

      - name: Swap EUN from pre prod to prod
        uses: azure/cli@v2.2.0
        with:
          azcliversion: 2.75.0
          inlineScript: |
            set -x
            az 'webapp' deployment slot swap \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --slot preprod \
              --target-slot production
        env:
          AZURE_CORE_USE_MSAL_HTTP_CACHE: false

      - name: Delete zip file
        run: rm next.zip
