name: PR infrastructure

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  # injecting the uri is subject to race condition so we need to limit the concurrency
  group: 'pr-infrastructure'
  cancel-in-progress: false

env:
  ARM_TENANT_ID: bd5c6713-7399-4b31-be79-78f2d078e543
  CLIENT_ID: 2c640eb1-36ce-4c8a-be67-0559df1722f5

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy-pr-infrastructure:
    name: Deploy PR infrastructure
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment:
      name: deveun
    steps:
      - uses: actions/checkout@v4
      - name: Check composite parameter for the reusable pipeline
        id: check-composite-vars
        uses: DigitalInnovation/brightcloud/.github/actions/check-layer-runtime-type@feat/oidcn
      - id: dynamic-env-name
        uses: DigitalInnovation/brightcloud/.github/actions/get-app-name@feat/oidcn
      - name: Check infra exists
        continue-on-error: true
        id: check-pr-infra-exists
        run: |
          set +e
          echo "should_build_env=false" >> "$GITHUB_OUTPUT"
          curl -I https://${{ steps.dynamic-env-name.outputs.dynamic-env-name }}.azurewebsites.net
          EXITCODE=$?
          if [ "$EXITCODE" -eq "6" ]; then
            echo "should_build_env=true" >> "$GITHUB_OUTPUT"
          fi
          set -e
          exit 0

      - name: Login via Azure CLI
        if: steps.check-pr-infra-exists.outputs.should_build_env == 'true'
        uses: azure/login@v1.6.1
        with:
          creds: '{"clientId": "${{ env.CLIENT_ID }}" , "clientSecret": "${{ secrets.SP_PASSWORD }}", "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}", "tenantId": "bd5c6713-7399-4b31-be79-78f2d078e543"}'

      - name: Inject uri to redirect uris if needed
        if: steps.check-pr-infra-exists.outputs.should_build_env == 'true'
        run: |
          set -x
          # this script is adapted from: https://stackoverflow.com/questions/76388274/updating-web-redirect-uri-of-azure-ad-app-registration

          new_uri="https://${{ steps.dynamic-env-name.outputs.dynamic-env-name }}.azurewebsites.net/api/auth/callback/azure-ad"

          existing_redirect_uris=$(az ad app show --id "${{ env.CLIENT_ID }}" --query "[web.redirectUris]" --output tsv)
          echo "$existing_redirect_uris"

          # Check if the new URI is already in the list
          if [[ $existing_redirect_uris == *$new_uri* ]]; then
              echo "The URI $new_uri is already in the list"
          else
              echo "Adding the URI $new_uri to the list"
              az ad app update --id "${{ env.CLIENT_ID }}" --web-redirect-uris $existing_redirect_uris $new_uri
          fi

      - name: Set up environment variables
        if: steps.check-pr-infra-exists.outputs.should_build_env == 'true'
        id: set-env
        run: |
          set -x

          secrets=$(echo '${{ toJSON(secrets) }}' | jq -c --arg _NEXTAUTH_URL https://${{ steps.dynamic-env-name.outputs.dynamic-env-name }}.azurewebsites.net/api/auth/ '. + {_NEXTAUTH_URL: $_NEXTAUTH_URL}' )
          echo "secrets=$secrets" >> "$GITHUB_OUTPUT"

      - name: Deploy PR infrastructure
        if: steps.check-pr-infra-exists.outputs.should_build_env == 'true'
        uses: DigitalInnovation/brightcloud/.github/actions/webapp-dynamic-env-oidc@feat/oidcn
        with:
          NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          SAML_GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
          BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
          ALL_SECRETS: ('${{ steps.set-env.outputs.secrets }}')
          DYNAMIC_ENV_APP_NAME: ${{ steps.dynamic-env-name.outputs.dynamic-env-name }}
          APP_NAME: ${{ steps.dynamic-env-name.outputs.app-name }}
          TTL: 24h
          MAX_APPS_IN_ASP: 25
          BRIGHTCLOUD_REF: feat/oidcn
          APP_STACK: ${{ steps.check-composite-vars.outputs.linux-fx-version }}
