name: PR infrastructure cleanup

on:
  pull_request:
    types: [closed]

concurrency:
  # injecting the uri is subject to race condition so we need to limit the concurrency
  group: 'pr-infrastructure'
  cancel-in-progress: false

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  cleanup-pr-infrastructure:
    name: Cleanup PR infrastructure
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment:
      name: deveun
    steps:
      - uses: actions/checkout@v4
      - name: Check composite parameter for the reusable pipeline
        id: check-composite-vars
        uses: DigitalInnovation/brightcloud/.github/actions/check-layer-runtime-type@feat/oidcn
      - id: dynamic-env-name
        uses: DigitalInnovation/brightcloud/.github/actions/get-app-name@feat/oidcn
      - name: Log in via Azure CLI as federated SP
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.FEDERATED_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.FEDERATED_AD_TENANT_ID }}
          subscription-id: ${{ secrets.FEDERATED_SUBSCRIPTION_ID }}

      - name: Remove URIs from azure app registration
        run: |
          set -x
          app_name="prs-ar-trading-hub"

          object_id="$(az ad app list --filter "displayname eq '$app_name'" | jq -r '.[0].id')"
          remove_uri="https://${{ steps.dynamic-env-name.outputs.dynamic-env-name }}.azurewebsites.net/api/auth/callback/azure-ad"

          # Get list of existing redirect URIs and already remove selected with sed from that list
          remaining_redirect_uris=$(az ad app show --id "${object_id}" --query "[web.redirectUris]" --output tsv | sed "s|$remove_uri||g")
          echo "$remaining_redirect_uris"
          az ad app update --id "${object_id}" --web-redirect-uris $remaining_redirect_uris

      - name: Remove secret from azure app registration
        run: |
          set -x
          app_name="prs-ar-trading-hub"

          object_id="$(az ad app list --filter "displayname eq '$app_name'" | jq -r '.[0].id')"
          secret_display_name="${{ steps.dynamic-env-name.outputs.dynamic-env-name }}"

          existing_secret_display_key_id=$(az ad app show --id "${object_id}" --query "[passwordCredentials]" | jq -r '.[][] | select( .displayName | contains("${{ steps.dynamic-env-name.outputs.dynamic-env-name }}")).keyId')

          # Check if existing_secret_display_key_id is empty
          if [[ -z $existing_secret_display_key_id ]]; then
              echo "The secret for ${{ steps.dynamic-env-name.outputs.dynamic-env-name }} is not found"
          else
              echo "Deleting the secret for ${{ steps.dynamic-env-name.outputs.dynamic-env-name }} with id $existing_secret_display_key_id"
              az ad app credential delete --id "${object_id}" --key-id $existing_secret_display_key_id
          fi
