name: PR infrastructure

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  # injecting the uri is subject to race condition so we need to limit the concurrency
  group: 'pr-infrastructure'
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-pr-app-infrastructure:
    name: Deploy PR app infrastructure
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment:
      name: deveun
    steps:
      - uses: actions/checkout@v4
      - name: Log in via Azure CLI as federated SP
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.FEDERATED_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.FEDERATED_AD_TENANT_ID }}
          subscription-id: ${{ secrets.FEDERATED_SUBSCRIPTION_ID }}

      - name: Check if app exists and create if not
        shell: bash
        id: check-app-exists
        run: |
          set -x

          app_name="prs-ar-trading-hub"

          number_of_apps="$(az ad app list --filter "displayname eq '$app_name'" | jq length)"
          if (( "$number_of_apps" >= 1 )); then
              echo "App exists"
          else
              echo "App does not exist, creating..."
              az ad app create --display-name "$app_name"
          fi

          object_id="$(az ad app list --filter "displayname eq '$app_name'" | jq -r '.[0].id')"
          app_id="$(az ad app list --filter "displayname eq '$app_name'" | jq -r '.[0].appId')"

          number_of_required_resource_access_records="$(az ad app show --id $object_id --query "requiredResourceAccess" | jq length)"

          if (( "$number_of_required_resource_access_records" >= 1 )); then
              echo "Required resource access records exist"
          else
              echo "Required resource access records do not exist, adding..."
              echo '
          - resourceAppId: 00000003-0000-0000-c000-000000000000
            resourceAccess:
            - id: e1fe6dd8-ba31-4d61-89e7-88639da4683d # User.Read
              type: Scope
            - id: 7427e0e9-2fba-42fe-b0c0-848c9e6a8182 # offline_access
              type: Scope
            - id: 37f7f235-527c-4136-accd-4a02d197296e # openid
              type: Scope
            - id: 14dad69e-099b-42c9-810b-d002981feec1 # profile
              type: Scope
          ' | yq -o=json '.' > manifest.json
              cat manifest.json
              az ad app update --id "$object_id" --required-resource-accesses @./manifest.json
          fi

          echo "object-id=$object_id" >> "$GITHUB_OUTPUT"
          echo "app-id=$app_id" >> "$GITHUB_OUTPUT"

      - name: Check composite parameter for the reusable pipeline
        id: check-composite-vars
        uses: DigitalInnovation/brightcloud/.github/actions/check-layer-runtime-type@feat/oidcn
      - id: dynamic-env-name
        uses: DigitalInnovation/brightcloud/.github/actions/get-app-name@feat/oidcn
      - name: Check infra exists
        continue-on-error: true
        id: check-pr-infra-exists
        run: |
          set +e
          echo "should_build_env=false" >> "$GITHUB_OUTPUT"
          curl -I https://${{ steps.dynamic-env-name.outputs.dynamic-env-name }}.azurewebsites.net
          EXITCODE=$?
          if [ "$EXITCODE" -eq "6" ]; then
            echo "should_build_env=true" >> "$GITHUB_OUTPUT"
          fi
          set -e
          exit 0

      - name: Inject secrets to the app registration if needed
        if: steps.check-pr-infra-exists.outputs.should_build_env == 'true'
        id: inject-secrets
        run: |
          set -x
          existing_secret_display_name=$(az ad app show --id "${{ steps.check-app-exists.outputs.object-id }}" --query "[passwordCredentials]" | jq -c '.[][] | select( .displayName | contains("${{ steps.dynamic-env-name.outputs.dynamic-env-name }}")).displayName')

          if [[ $existing_secret_display_name == *"${{ steps.dynamic-env-name.outputs.dynamic-env-name }}"* ]]; then
              echo "The secret for ${{ steps.dynamic-env-name.outputs.dynamic-env-name }} is already in the list, recreating it..."
              existing_secret_display_key_id=$(az ad app show --id "${{ steps.check-app-exists.outputs.object-id }}" --query "[passwordCredentials]" | jq -r '.[][] | select( .displayName | contains("${{ steps.dynamic-env-name.outputs.dynamic-env-name }}")).keyId')
              az ad app credential delete --id "${{ steps.check-app-exists.outputs.object-id }}" --key-id $existing_secret_display_key_id
          fi

          echo "Adding the secret for ${{ steps.dynamic-env-name.outputs.dynamic-env-name }} to the list"
          new_password=$(az ad app credential reset --id "${{ steps.check-app-exists.outputs.object-id }}" --append --display-name "${{ steps.dynamic-env-name.outputs.dynamic-env-name }}" | jq -r '.password')

          secrets=$(echo '${{ toJSON(secrets) }}' | jq -c \
            --arg _NEXTAUTH_URL https://${{ steps.dynamic-env-name.outputs.dynamic-env-name }}.azurewebsites.net/api/auth/ \
            --arg _AZURE_AD_CLIENT_ID "${{ steps.check-app-exists.outputs.app-id }}" \
            --arg _AZURE_AD_CLIENT_SECRET "$new_password" \
            --arg _AZURE_AD_TENANT_ID bd5c6713-7399-4b31-be79-78f2d078e543 \
            '. + {_NEXTAUTH_URL: $_NEXTAUTH_URL, _AZURE_AD_CLIENT_ID: $_AZURE_AD_CLIENT_ID, _AZURE_AD_CLIENT_SECRET: $_AZURE_AD_CLIENT_SECRET, _AZURE_AD_TENANT_ID: $_AZURE_AD_TENANT_ID }' )

          echo "new-password=$new_password" >> "$GITHUB_OUTPUT"
          echo "secrets=$secrets" >> "$GITHUB_OUTPUT"

      - name: Inject uri to redirect uris if needed
        if: steps.check-pr-infra-exists.outputs.should_build_env == 'true'
        run: |
          set -x
          # this script is adapted from: https://stackoverflow.com/questions/76388274/updating-web-redirect-uri-of-azure-ad-app-registration

          new_uri="https://${{ steps.dynamic-env-name.outputs.dynamic-env-name }}.azurewebsites.net/api/auth/callback/azure-ad"

          existing_redirect_uris=$(az ad app show --id "${{ steps.check-app-exists.outputs.object-id }}" --query "[web.redirectUris]" --output tsv)
          echo "$existing_redirect_uris"

          # Check if the new URI is already in the list
          if [[ $existing_redirect_uris == *$new_uri* ]]; then
              echo "The URI $new_uri is already in the list"
          else
              echo "Adding the URI $new_uri to the list"
              az ad app update --id "${{ steps.check-app-exists.outputs.object-id }}" --web-redirect-uris $existing_redirect_uris $new_uri
          fi

      - name: Login via Azure CLI as Cloud9 own SP
        if: steps.check-pr-infra-exists.outputs.should_build_env == 'true'
        uses: azure/login@v1.6.1
        with:
          creds: '{"clientId": "2c640eb1-36ce-4c8a-be67-0559df1722f5" , "clientSecret": "${{ secrets.SP_PASSWORD }}", "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}", "tenantId": "bd5c6713-7399-4b31-be79-78f2d078e543"}'

      - name: Deploy PR infrastructure
        if: steps.check-pr-infra-exists.outputs.should_build_env == 'true'
        uses: DigitalInnovation/brightcloud/.github/actions/webapp-dynamic-env-oidc@feat/oidcn
        with:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
          SAML_GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
          BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
          ALL_SECRETS: ('${{ steps.inject-secrets.outputs.secrets }}')
          DYNAMIC_ENV_APP_NAME: ${{ steps.dynamic-env-name.outputs.dynamic-env-name }}
          APP_NAME: ${{ steps.dynamic-env-name.outputs.app-name }}
          TTL: 24h
          MAX_APPS_IN_ASP: 25
          BRIGHTCLOUD_REF: feat/oidcn
          APP_STACK: ${{ steps.check-composite-vars.outputs.linux-fx-version }}
