name: Release

on:
  repository_dispatch:
    types: [production-release]
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Get versions from package.json
        id: get-versions-from-package-json
        shell: bash
        run: |
          set -x
          NODE_VERSION=$(jq -r '.engines.node' < package.json)
          echo "node-version=${NODE_VERSION}" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-node@v4.0.4
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: '10'
        with:
          node-version: ${{ steps.get-versions-from-package-json.outputs.node-version }}
          cache: npm

      - name: add version.txt
        run: |
          set -x
          SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
          APP_VERSION=${SHORT_COMMIT_SHA}-${{ github.run_number }}
          echo "${APP_VERSION}" > ./public/version.txt
          ls -lA

      - name: npm install and build
        run: |
          set -x
          echo "npm version: $(npm --version)"
          echo "node version: $(node --version)"
          npm install
          NEXT_TELEMETRY_DISABLED=1 npm run build
        env:
          NEW_RELIC_APP_NAME: ${{ secrets.NEW_RELIC_APP_NAME }}
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}

      - name: Zip all files for upload between jobs
        # IMPORTANT: .next is a hidden folder and will NOT be included in the zip unless we specify it
        run: |
          cd .next/standalone
          zip next.zip ./* .next -qr

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .next/standalone/next.zip

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to Azure Web App (dev)
    environment:
      name: deveun
    steps:
      - uses: actions/checkout@v4
      - name: Get terraform settings
        id: get-tf-settings
        shell: bash
        run: |
          set -x
          STACK_VERSION="$(grep stack_version ./ci/infra/terraform/vars/common.tfvars | sed 's/[^0-9]*//g')"
          APP_NAME="dev-trading-hub"
          EUN_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-eun-layer3-rg"
          EUN_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-eun-layer4-rg"
          EUN_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}eunlayer4policywafpolicy"
          EUN_WAF_POLICY_NAME="${EUN_WAF_POLICY_NAME//"-"/""}"
          EUN_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-eun-layer3-app"
          EUW_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-euw-layer3-rg"
          EUW_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-euw-layer4-rg"
          EUW_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}euwlayer4policywafpolicy"
          EUW_WAF_POLICY_NAME="${EUW_WAF_POLICY_NAME//"-"/""}"
          EUW_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-euw-layer3-app"
          {
            echo "eun-resource-group-alias-layer3=${EUN_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "eun-resource-group-alias-layer4=${EUN_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "eun-waf-policy-name=${EUN_WAF_POLICY_NAME}"
            echo "eun-app-alias=${EUN_APP_ALIAS}"
            echo "euw-resource-group-alias-layer3=${EUW_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "euw-resource-group-alias-layer4=${EUW_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "euw-waf-policy-name=${EUW_WAF_POLICY_NAME}"
            echo "euw-app-alias=${EUW_APP_ALIAS}"
          } >> "$GITHUB_OUTPUT"

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: '{"clientId": "${{ secrets.SP_CLIENT_ID }}", "clientSecret": "${{ secrets.SP_PASSWORD }}", "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}", "tenantId": "bd5c6713-7399-4b31-be79-78f2d078e543"}'

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Set up environment variables
        uses: azure/cli@v2
        with:
          azcliversion: 2.53.1
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --settings \
              "MERCHANDISING_API_BASEURL=https://api-dev.marksandspencer.com/merchandising" \
              "MERCHANDISING_API_APIGEE_KEY=${{ secrets._MERCHANDISING_API_APIGEE_KEY }}" \
              "NEXTAUTH_SECRET=${{ secrets._NEXTAUTH_SECRET }}" \
              "NEXTAUTH_URL=https://dev-merchandising-hub.search.marksandspencer.app/api/auth" \
              "AZURE_AD_CLIENT_ID=${{ secrets._AZURE_AD_CLIENT_ID }}" \
              "AZURE_AD_CLIENT_SECRET=${{ secrets._AZURE_AD_CLIENT_SECRET }}" \
              "AZURE_AD_TENANT_ID=${{ secrets._AZURE_AD_TENANT_ID }}" \
              "NEW_RELIC_APP_NAME=${{ secrets._NEW_RELIC_APP_NAME }}" \
              "NEW_RELIC_LICENSE_KEY=${{ secrets._NEW_RELIC_LICENSE_KEY }}"

      - name: Deploy to Azure Web Apps
        shell: bash
        run: |
          set -x
          az webapp deployment source config-zip \
            --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
            --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
            --src ./next.zip --timeout 360

      - name: Delete zip file
        run: rm next.zip

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    if: false
    name: Deploy to Azure Web App (production)
    environment:
      name: prodeun
    steps:
      - uses: actions/checkout@v4
      - name: Get terraform settings
        id: get-tf-settings
        shell: bash
        run: |
          set -x
          STACK_VERSION="$(grep stack_version ./ci/infra/terraform/vars/common.tfvars | sed 's/[^0-9]*//g')"
          APP_NAME="prod-trading-hub"
          EUN_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-eun-layer3-rg"
          EUN_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-eun-layer4-rg"
          EUN_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}eunlayer4policywafpolicy"
          EUN_WAF_POLICY_NAME="${EUN_WAF_POLICY_NAME//"-"/""}"
          EUN_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-eun-layer3-app"
          EUW_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-euw-layer3-rg"
          EUW_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-euw-layer4-rg"
          EUW_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}euwlayer4policywafpolicy"
          EUW_WAF_POLICY_NAME="${EUW_WAF_POLICY_NAME//"-"/""}"
          EUW_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-euw-layer3-app"
          {
            echo "eun-resource-group-alias-layer3=${EUN_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "eun-resource-group-alias-layer4=${EUN_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "eun-waf-policy-name=${EUN_WAF_POLICY_NAME}"
            echo "eun-app-alias=${EUN_APP_ALIAS}"
            echo "euw-resource-group-alias-layer3=${EUW_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "euw-resource-group-alias-layer4=${EUW_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "euw-waf-policy-name=${EUW_WAF_POLICY_NAME}"
            echo "euw-app-alias=${EUW_APP_ALIAS}"
          } >> "$GITHUB_OUTPUT"

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: '{"clientId": "${{ secrets.SP_CLIENT_ID }}", "clientSecret": "${{ secrets.SP_PASSWORD }}", "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}", "tenantId": "bd5c6713-7399-4b31-be79-78f2d078e543"}'

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Set up environment variables
        uses: azure/cli@v2
        with:
          azcliversion: 2.53.1
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --settings \
              "MERCHANDISING_API_BASEURL=https://api.marksandspencer.com/merchandising" \
              "MERCHANDISING_API_APIGEE_KEY=${{ secrets._MERCHANDISING_API_APIGEE_KEY }}" \
              "NEXTAUTH_SECRET=${{ secrets._NEXTAUTH_SECRET }}" \
              "NEXTAUTH_URL=https://merchandising-hub.search.marksandspencer.app/api/auth" \
              "AZURE_AD_CLIENT_ID=${{ secrets._AZURE_AD_CLIENT_ID }}" \
              "AZURE_AD_CLIENT_SECRET=${{ secrets._AZURE_AD_CLIENT_SECRET }}" \
              "AZURE_AD_TENANT_ID=${{ secrets._AZURE_AD_TENANT_ID }}" \
              "NEW_RELIC_APP_NAME=${{ secrets._NEW_RELIC_APP_NAME }}" \
              "NEW_RELIC_LICENSE_KEY=${{ secrets._NEW_RELIC_LICENSE_KEY }}" \

      - name: Deploy to Azure Web Apps slot
        uses: azure/cli@v2
        with:
          azcliversion: 2.53.1
          inlineScript: |
            az webapp deploy \
            --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
            --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
            --slot preprod \
            --src-path ./next.zip \
            --type zip \
            --async true

      - name: Validate version number
        uses: nick-fields/retry@v3.0.0
        with:
          timeout_seconds: 20
          max_attempts: 10
          retry_wait_seconds: 10
          command: |
            set -x
            SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
            VERSION_CHECK_URL="https://stage-merchandising-hub.search.marksandspencer.app/version.txt"
            VERSION=$(curl "${VERSION_CHECK_URL}")
            APP_COMMIT_SHA=${SHORT_COMMIT_SHA}
            echo ${VERSION} | grep ${APP_COMMIT_SHA}

      - name: Swap EUN from pre prod to prod
        uses: azure/cli@v2.1.0
        with:
          azcliversion: 2.53.1
          inlineScript: |
            set -x
            az 'webapp' deployment slot swap \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --slot preprod \
              --target-slot production

      - name: Delete zip file
        run: rm next.zip
