name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: Prepare node and install dependencies
        uses: ./.github/actions/prepare

      - name: add version.txt
        run: |
          set -x
          SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
          APP_VERSION=${SHORT_COMMIT_SHA}-${{ github.run_number }}
          echo "${APP_VERSION}" > ./public/version.txt
          ls -lA

      - name: Build
        run: |
          set -x
          echo "node version: $(node --version)"
          NEXT_TELEMETRY_DISABLED=1 pnpm run build
        env:
          DYNATRACE_RUM_SCRIPT_URL_DEV: ${{ secrets.DYNATRACE_RUM_SCRIPT_URL_DEV }}
          DYNATRACE_RUM_SCRIPT_URL_PROD: ${{ secrets.DYNATRACE_RUM_SCRIPT_URL_PROD }}
          CLARITY_KEY: ${{ secrets.CLARITY_KEY }}

      - name: Validate standalone output
        run: |
          set -euxo pipefail
          ls -la .next/standalone
          test -f .next/standalone/server.js

      - name: Zip all files for upload between jobs
        run: |
          cd .next/standalone
          zip -qr next.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v7
        with:
          name: node-app
          path: .next/standalone/next.zip
  determine-runner-nonprod:
    environment: Nonprod
    runs-on: ubuntu-latest
    outputs:
      runner_label: ${{ steps.set-runner.outputs.runner_label }}
    steps:
      - id: set-runner
        run: |
          echo "runner_label=${{ vars.GIT_ACTIONS_RUNNER_LABEL || 'ubuntu-latest' }}" >> "$GITHUB_OUTPUT"

  deploy-dev:
    runs-on: ${{ needs.determine-runner-nonprod.outputs.runner_label }}
    permissions:
      contents: read
      id-token: write
    needs: [build, determine-runner-nonprod]
    name: Deploy to Azure Web App (dev)
    environment:
      name: deveun
    steps:
      - uses: actions/checkout@v7
      - name: Get terraform settings
        id: get-tf-settings
        shell: bash
        run: |
          set -x
          STACK_VERSION="$(grep stack_version ./ci/infra/terraform/vars/common.tfvars | sed 's/[^0-9]*//g')"
          APP_NAME="dev-trading-hub"
          EUN_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-eun-layer3-rg"
          EUN_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-eun-layer4-rg"
          EUN_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}eunlayer4policywafpolicy"
          EUN_WAF_POLICY_NAME="${EUN_WAF_POLICY_NAME//"-"/""}"
          EUN_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-eun-layer3-app"
          EUW_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-euw-layer3-rg"
          EUW_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-euw-layer4-rg"
          EUW_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}euwlayer4policywafpolicy"
          EUW_WAF_POLICY_NAME="${EUW_WAF_POLICY_NAME//"-"/""}"
          EUW_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-euw-layer3-app"
          {
            echo "eun-resource-group-alias-layer3=${EUN_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "eun-resource-group-alias-layer4=${EUN_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "eun-waf-policy-name=${EUN_WAF_POLICY_NAME}"
            echo "eun-app-alias=${EUN_APP_ALIAS}"
            echo "euw-resource-group-alias-layer3=${EUW_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "euw-resource-group-alias-layer4=${EUW_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "euw-waf-policy-name=${EUW_WAF_POLICY_NAME}"
            echo "euw-app-alias=${EUW_APP_ALIAS}"
          } >> "$GITHUB_OUTPUT"

      - name: Login via Azure CLI
        uses: azure/login@v3.0.1
        with:
          client-id: ${{ secrets._AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets._AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: node-app

      - name: Set up environment variables
        uses: azure/cli@v3
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --settings \
              "MERCHANDISING_API_BASEURL=https://api-dev.marksandspencer.com/merchandising" \
              "MERCHANDISING_API_APIGEE_KEY=${{ secrets._MERCHANDISING_API_APIGEE_KEY }}" \
              "NEXTAUTH_SECRET=${{ secrets._NEXTAUTH_SECRET }}" \
              "NEXTAUTH_URL=https://dev-merchandising-hub.search.marksandspencer.app/api/auth" \
              "AZURE_AD_CLIENT_ID=${{ secrets._AZURE_AD_CLIENT_ID }}" \
              "AZURE_AD_CLIENT_SECRET=${{ secrets._AZURE_AD_CLIENT_SECRET }}" \
              "AZURE_AD_TENANT_ID=${{ secrets._AZURE_AD_TENANT_ID }}" \
              "FLAGS_ALLOWED_EMAILS=${{ secrets.FLAGS_ALLOWED_EMAILS }}" \
              "WEBSITES_PORT=4200"

      - name: Deploy to Azure Web Apps
        uses: azure/cli@v3
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az webapp deploy \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --src-path ./next.zip \
              --type zip \
              --async true

      - name: Validate deployment
        uses: nick-fields/retry@v4.0.0
        with:
          timeout_seconds: 20
          max_attempts: 15
          retry_wait_seconds: 10
          command: |
            set -x
            SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
            VERSION_CHECK_URL="https://dev-merchandising-hub.search.marksandspencer.app/version.txt"
            VERSION=$(curl -sf "${VERSION_CHECK_URL}")
            echo "Deployed version: ${VERSION}"
            echo ${VERSION} | grep ${SHORT_COMMIT_SHA}

      - name: Delete zip file
        run: rm next.zip

  dev-e2e-tests:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    name: Smoke tests (dev)
    env:
      SMOKE_TEST_TOKEN: ${{ secrets.SMOKE_TEST_TOKEN }}
      MERCHANDISING_API_BASEURL: https://api-dev.marksandspencer.com/merchandising
      MERCHANDISING_API_APIGEE_KEY: ${{ secrets.MERCHANDISING_API_DEV_APIGEE_KEY }}
      NEXTAUTH_URL: http://localhost:3000/api/auth
      NEXTAUTH_SECRET: ${{ secrets._NEXTAUTH_SECRET }}
      AZURE_AD_CLIENT_ID: ${{ secrets._AZURE_AD_CLIENT_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets._AZURE_AD_TENANT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets._AZURE_AD_CLIENT_SECRET }}
      NEXT_PUBLIC_AUTO_LOGIN: false
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Prepare node and install dependencies
        uses: ./.github/actions/prepare
      - name: Build app
        run: pnpm run build
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: Run Playwright tests
        run: pnpm exec playwright test --project=smoke
      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  automated-cab-start:
    name: Automated CAB Start
    uses: DigitalInnovation/change-management-github-workflows/.github/workflows/start-change-request.yml@v2
    needs: [build, deploy-dev, dev-e2e-tests]
    permissions:
      pull-requests: write
    with:
      portfolio: 'Customer Engagement'
      app-name: 'Merchandising Hub'
      use-helix-qa-environment: false
    secrets:
      helix-password: ${{ secrets.BMC_HELIX_API_PASSWORD }}
      dynatrace-api-token: ${{ secrets.DYNATRACE_ACCESS_TOKEN_PROD }}

  determine-runner-prod:
    environment: Prod
    runs-on: ubuntu-latest
    needs: automated-cab-start
    outputs:
      runner_label: ${{ steps.set-runner.outputs.runner_label }}
    steps:
      - id: set-runner
        run: |
          echo "runner_label=${{ vars.GIT_ACTIONS_RUNNER_LABEL || 'ubuntu-latest' }}" >> "$GITHUB_OUTPUT"

  deploy-prod:
    runs-on: ${{ needs.determine-runner-prod.outputs.runner_label }}
    permissions:
      contents: read
      id-token: write
    needs:
      [
        build,
        deploy-dev,
        dev-e2e-tests,
        automated-cab-start,
        determine-runner-prod,
      ]
    name: Deploy to Azure Web App (production)
    environment:
      name: prodeun
    steps:
      - uses: actions/checkout@v7
      - name: Get terraform settings
        id: get-tf-settings
        shell: bash
        run: |
          set -x
          STACK_VERSION="$(grep stack_version ./ci/infra/terraform/vars/common.tfvars | sed 's/[^0-9]*//g')"
          APP_NAME="prod-trading-hub"
          EUN_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-eun-layer3-rg"
          EUN_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-eun-layer4-rg"
          EUN_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}eunlayer4policywafpolicy"
          EUN_WAF_POLICY_NAME="${EUN_WAF_POLICY_NAME//"-"/""}"
          EUN_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-eun-layer3-app"
          EUW_RESOURCE_GROUP_ALIAS_LAYER3="${APP_NAME}-v${STACK_VERSION}-euw-layer3-rg"
          EUW_RESOURCE_GROUP_ALIAS_LAYER4="${APP_NAME}-v${STACK_VERSION}-euw-layer4-rg"
          EUW_WAF_POLICY_NAME="${APP_NAME}v${STACK_VERSION}euwlayer4policywafpolicy"
          EUW_WAF_POLICY_NAME="${EUW_WAF_POLICY_NAME//"-"/""}"
          EUW_APP_ALIAS="${APP_NAME}-v${STACK_VERSION}-euw-layer3-app"
          {
            echo "eun-resource-group-alias-layer3=${EUN_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "eun-resource-group-alias-layer4=${EUN_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "eun-waf-policy-name=${EUN_WAF_POLICY_NAME}"
            echo "eun-app-alias=${EUN_APP_ALIAS}"
            echo "euw-resource-group-alias-layer3=${EUW_RESOURCE_GROUP_ALIAS_LAYER3}"
            echo "euw-resource-group-alias-layer4=${EUW_RESOURCE_GROUP_ALIAS_LAYER4}"
            echo "euw-waf-policy-name=${EUW_WAF_POLICY_NAME}"
            echo "euw-app-alias=${EUW_APP_ALIAS}"
          } >> "$GITHUB_OUTPUT"

      - name: Login via Azure CLI
        uses: azure/login@v3.0.1
        with:
          client-id: ${{ secrets._AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets._AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: node-app

      - name: Set up environment variables
        uses: azure/cli@v3
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --settings \
              "MERCHANDISING_API_BASEURL=https://api.marksandspencer.com/merchandising" \
              "MERCHANDISING_API_APIGEE_KEY=${{ secrets._MERCHANDISING_API_APIGEE_KEY }}" \
              "NEXTAUTH_SECRET=${{ secrets._NEXTAUTH_SECRET }}" \
              "NEXTAUTH_URL=https://merchandising-hub.search.marksandspencer.app/api/auth" \
              "AZURE_AD_CLIENT_ID=${{ secrets._AZURE_AD_CLIENT_ID }}" \
              "AZURE_AD_CLIENT_SECRET=${{ secrets._AZURE_AD_CLIENT_SECRET }}" \
              "AZURE_AD_TENANT_ID=${{ secrets._AZURE_AD_TENANT_ID }}" \
              "CLARITY_KEY=${{ secrets.CLARITY_KEY }}" \
              "FLAGS_ALLOWED_EMAILS=${{ secrets.FLAGS_ALLOWED_EMAILS }}" \
              "WEBSITES_PORT=4200"

      - name: Deploy to Azure Web Apps slot
        uses: azure/cli@v3
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az webapp deploy \
            --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
            --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
            --slot preprod \
            --src-path ./next.zip \
            --type zip \
            --async true

      - name: Validate version number
        uses: nick-fields/retry@v4.0.0
        with:
          timeout_seconds: 20
          max_attempts: 10
          retry_wait_seconds: 10
          command: |
            set -x
            SHORT_COMMIT_SHA=$(git rev-parse --short HEAD)
            VERSION_CHECK_URL="https://prod-trading-hub-v1-eun-layer3-app-preprod.azurewebsites.net/version.txt"
            VERSION=$(curl "${VERSION_CHECK_URL}")
            APP_COMMIT_SHA=${SHORT_COMMIT_SHA}
            echo ${VERSION} | grep ${APP_COMMIT_SHA}

      - name: Swap EUN from pre prod to prod
        uses: azure/cli@v3.0.0
        with:
          azcliversion: 2.75.0
          inlineScript: |
            set -x
            az 'webapp' deployment slot swap \
              --name ${{ steps.get-tf-settings.outputs.eun-app-alias }} \
              --resource-group ${{ steps.get-tf-settings.outputs.eun-resource-group-alias-layer3 }} \
              --slot preprod \
              --target-slot production

      - name: Delete zip file
        run: rm next.zip

  sync-branch:
    runs-on: ubuntu-latest
    needs: [deploy-prod]
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> hotfix
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: hotfix
          github_token: ${{ secrets.GITHUB_TOKEN }}
  automated-cab-end:
    name: Automated CAB End
    uses: DigitalInnovation/change-management-github-workflows/.github/workflows/complete-change-request.yml@v2
    needs: [automated-cab-start, deploy-prod]
    permissions:
      pull-requests: write
    with:
      portfolio: 'Customer Engagement'
      app-name: 'Merchandising Hub'
      use-helix-qa-environment: false
    secrets:
      helix-password: ${{ secrets.BMC_HELIX_API_PASSWORD }}
      dynatrace-api-token: ${{ secrets.DYNATRACE_ACCESS_TOKEN_PROD }}

  automated-cab-close:
    name: Automated CAB Close
    uses: DigitalInnovation/change-management-github-workflows/.github/workflows/close-change-request.yml@v2
    needs: [automated-cab-start, deploy-prod]
    if: ${{ always() && needs.deploy-prod.result == 'failure' }}
    with:
      portfolio: 'Customer Engagement'
      app-name: 'Merchandising Hub'
      close-reason: 'Unsuccessful'
    secrets:
      helix-password: ${{ secrets.BMC_HELIX_API_PASSWORD }}
      dynatrace-api-token: ${{ secrets.DYNATRACE_ACCESS_TOKEN_PROD }}
