name: Smoke tests

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 7-20 * * 1-5' # Every 15 minutes Mon-Fri 7am-8pm GMT https://crontab.guru/#*/15_7-20_*_*_1-5

env:
  GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}

jobs:
  build:
    name: Checkout app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare node and install dependencies
        uses: ./.github/actions/prepare

  end-to-end-smoke-tests:
    runs-on: ubuntu-latest
    name: E2E Smoke Tests
    env:
      SMOKE_TEST_TOKEN: ${{ secrets.SMOKE_TEST_TOKEN }}
      MERCHANDISING_API_BASEURL: https://api-dev.marksandspencer.com/merchandising
      MERCHANDISING_API_APIGEE_KEY: ${{ secrets.MERCHANDISING_API_DEV_APIGEE_KEY }}
      NEXTAUTH_URL: http://localhost:3000/api/auth
      NEXTAUTH_SECRET: ${{ secrets._NEXTAUTH_SECRET }}
      AZURE_AD_CLIENT_ID: ${{ secrets._AZURE_AD_CLIENT_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets._AZURE_AD_TENANT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets._AZURE_AD_CLIENT_SECRET }}
      NEXT_PUBLIC_AUTO_LOGIN: false
      NEW_RELIC_LICENSE_KEY: ${{ secrets._NEW_RELIC_LICENSE_KEY }}
      NEW_RELIC_APP_NAME: ${{ secrets._NEW_RELIC_APP_NAME }}
      DYNATRACE_URL: ${{ secrets.DYNATRACE_URL }}
      DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test --project=smoke
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Report results to New Relic & Dynatrace
        if: ${{ always() }}
        run: |
          set -e
          TEST_RESULTS=$(cat test-results.json | jq '.stats')
          TOTAL_TESTS=$(echo $TEST_RESULTS | jq '.expected + .unexpected')
          PASSED=$(echo $TEST_RESULTS | jq '.expected')
          FAILED=$(echo $TEST_RESULTS | jq '.unexpected')
          DURATION=$(echo $TEST_RESULTS | jq '.duration')
          TIMESTAMP=$(date +%s)
          RUN_DATE=$(date -u +"%d %B %Y %H:%M")
          DAY=$(date -u +"%d")

          # Add ordinal suffix to the day
          case "${DAY}" in
            1|21|31) ORDINAL="st";;
            2|22) ORDINAL="nd";;
            3|23) ORDINAL="rd";;
            *) ORDINAL="th";;
          esac

          FORMATTED_RUN_DATE="$(date -u +"${DAY}${ORDINAL} %B %Y %H:%M UTC")"
          NEW_RELIC_APP_NAME="${{ secrets.NEW_RELIC_APP_NAME }}"
          NEW_RELIC_LICENSE_KEY="${{ secrets.NEW_RELIC_LICENSE_KEY }}"
          NEW_RELIC_ACCOUNT_ID="${{ secrets.NEW_RELIC_ACCOUNT_ID }}"
          curl -X POST "https://insights-collector.newrelic.com/v1/accounts/$NEW_RELIC_ACCOUNT_ID/events" \
            -H "X-Insert-Key: $NEW_RELIC_LICENSE_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "eventType": "TradingHubSmokeTestResults",
              "appName": "'"$NEW_RELIC_APP_NAME"'",
              "runDateTime": "'"${FORMATTED_RUN_DATE}"'",
              "totalTests": '"$TOTAL_TESTS"',
              "passed": '"$PASSED"',
              "failed": '"$FAILED"',
              "duration": '"$DURATION"',
              "timestamp": '"$TIMESTAMP"'
            }'

          DYNATRACE_URL="${{ secrets.DYNATRACE_URL }}"
          DYNATRACE_API_TOKEN="${{ secrets.DYNATRACE_API_TOKEN }}"
          SERVICE_NAME="trading-hub"

          curl -X POST "$DYNATRACE_URL/api/v2/events/ingest" \
            -H "Authorization: Api-Token $DYNATRACE_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "eventType": "CUSTOM_ANNOTATION",
              "title": "Smoke Test Results for '"$SERVICE_NAME"'",
              "description": "Results of the smoke tests run on '"$FORMATTED_RUN_DATE"'",
              "properties": {
                "serviceName": "'"$SERVICE_NAME"'",
                "totalTests": '"$TOTAL_TESTS"',
                "passed": '"$PASSED"',
                "failed": '"$FAILED"',
                "duration": '"$DURATION"',
                "timestamp": '"$TIMESTAMP"'
              },
              "attachRules": {
                "tagRule": [
                  {
                    "meTypes": ["SERVICE"],
                    "tags": [
                      {
                        "key": "service",
                        "value": "'"$SERVICE_NAME"'"
                      },
                      {
                        "key": "environment",
                        "value": "dev"
                      }
                    ]
                  }
                ]
              }
            }'
