name: Smoke tests (production)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 4-20 * * 1-5' # Every 30 minutes Mon-Fri 4am-8pm GMT https://crontab.guru/#*/30_4-20_*_*_1-5.

env:
  GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
  DYNATRACE_PROD_URL: ${{ secrets.DYNATRACE_PROD_URL }}
  DYNATRACE_PROD_API_TOKEN: ${{ secrets.DYNATRACE_PROD_API_TOKEN }}

jobs:
  end-to-end-smoke-tests:
    runs-on: ubuntu-latest
    name: E2E Production Smoke Tests
    env:
      PROD_TEST_USER_PASSWORD: ${{ secrets.PROD_TEST_USER_PASSWORD }}
      PROD_TEST_USER: ${{ secrets.PROD_TEST_USER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        run: npx playwright test --project=production
      - uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Report results to Dynatrace
        if: ${{ always() }}
        run: |
          set -e
          TEST_RESULTS=$(jq '.stats' < test-results.json)
          TOTAL_TESTS=$(echo "$TEST_RESULTS" | jq '.expected + .unexpected + .flaky')
          PASSED=$(echo "$TEST_RESULTS" | jq '.expected')
          FAILED=$(echo "$TEST_RESULTS" | jq '.unexpected')
          FLAKY=$(echo "$TEST_RESULTS" | jq '.flaky')
          DURATION=$(echo "$TEST_RESULTS" | jq '.duration')
          TIMESTAMP=$(date +%s)
          DAY=$(date -u +"%d")

          # Add ordinal suffix to the day
          case "${DAY}" in
            1|21|31) ORDINAL="st";;
            2|22) ORDINAL="nd";;
            3|23) ORDINAL="rd";;
            *) ORDINAL="th";;
          esac

          FORMATTED_RUN_DATE="$(date -u +"${DAY}${ORDINAL} %B %Y %H:%M UTC")"
          DYNATRACE_URL="${{ secrets.DYNATRACE_PROD_URL }}"
          DYNATRACE_API_TOKEN="${{ secrets.DYNATRACE_PROD_API_TOKEN }}"
          SERVICE_NAME="trading-hub"

          curl -X POST "$DYNATRACE_URL/api/v2/events/ingest" \
            -H "Authorization: Api-Token $DYNATRACE_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "eventType": "CUSTOM_ANNOTATION",
              "title": "Smoke Test Results for '"$SERVICE_NAME"' (prod)",
              "description": "Results of the smoke tests run on '"$FORMATTED_RUN_DATE"'",
              "properties": {
                "serviceName": "'"$SERVICE_NAME"'",
                "totalTests": '"$TOTAL_TESTS"',
                "passed": '"$PASSED"',
                "failed": '"$FAILED"',
                "flaky": '"$FLAKY"',
                "duration": '"$DURATION"',
                "timestamp": '"$TIMESTAMP"'
              },
              "attachRules": {
                "tagRule": [
                  {
                    "meTypes": ["SERVICE"],
                    "tags": [
                      {
                        "key": "service",
                        "value": "'"$SERVICE_NAME"'"
                      },
                      {
                        "key": "environment",
                        "value": "prod"
                      }
                    ]
                  }
                ]
              }
            }'
